
import { Lesson } from './types';
import { createLesson } from './data_helpers';

// Química 2ª Série: 18 aulas por bimestre (Total 72)
export const quiLessonsB1: Lesson[] = [
  createLesson('g2-qui-b1-l1', 'L1: Revisão de Mol e Massa Molar', 'quimica',
    'O mol é a unidade fundamental de quantidade de matéria: 1 mol = 6,02×10²³ partículas. A massa molar (M) é a massa de 1 mol em g/mol, igual numericamente à massa atômica/molecular. Esses conceitos são a base de todos os cálculos estequiométricos avançados.',
    ['Calcule a massa molar do CaCO₃ (carbonato de cálcio — calcário).', 'Quantos mols há em 117g de NaCl?']),
  createLesson('g2-qui-b1-l2', 'L2: Fórmulas Empíricas e Moleculares', 'quimica',
    'A fórmula empírica mostra a proporção mais simples dos átomos (ex: CH₂O para glicose). A fórmula molecular mostra o número real de átomos (C₆H₁₂O₆ para glicose). Para determinar a fórmula molecular, divide-se a massa molar real pela massa da fórmula empírica.',
    ['Qual a fórmula empírica do benzeno (C₆H₆)?', 'Se a fórmula empírica de um composto é CH₂ e sua massa molar é 42 g/mol, qual é a fórmula molecular?']),
  createLesson('g2-qui-b1-l3', 'L3: Análise Elementar — Porcentagem em Massa', 'quimica',
    'A porcentagem em massa de cada elemento em um composto é calculada por: % = (n × M_elemento / M_composto) × 100. Essa análise é usada para determinar a composição de compostos desconhecidos e para controle de qualidade na indústria alimentícia e farmacêutica.',
    ['Calcule a porcentagem de nitrogênio na ureia CO(NH₂)₂ (fertilizante muito usado no agronegócio brasileiro).', 'Por que a análise elementar é importante para identificar adulterações em alimentos?']),
  createLesson('g2-qui-b1-l4', 'L4: Estequiometria — Relações Molares', 'quimica',
    'Os coeficientes de uma equação balanceada expressam a relação em mols entre reagentes e produtos. A proporção estequiométrica é a razão entre os coeficientes. A partir de mols, convertemos para gramas (× massa molar), litros de gás (× 22,4 L/mol em CNTP) ou número de partículas (× 6,02×10²³).',
    ['Na síntese da amônia (N₂ + 3H₂ → 2NH₃), quantos mols de NH₃ são produzidos a partir de 6 mols de H₂?', 'Por que a produção industrial de amônia (Processo Haber-Bosch) é tão importante para a agricultura mundial?']),
  createLesson('g2-qui-b1-l5', 'L5: Reagente Limitante — Cálculos', 'quimica',
    'Para determinar o reagente limitante: converta todos os reagentes em mols, use as proporções estequiométricas para calcular quantos mols de produto cada reagente produziria, e o reagente que produzir menos produto é o limitante. O produto obtido é determinado pelo reagente limitante.',
    ['Em uma reação com 4 mols de Fe e 3 mols de O₂ (4Fe + 3O₂ → 2Fe₂O₃), qual é o reagente limitante?', 'Quanto do reagente em excesso sobra ao final da reação do exercício anterior?']),
  createLesson('g2-qui-b1-l6', 'L6: Rendimento e Pureza em Cálculos Estequiométricos', 'quimica',
    'Rendimento (%) = (quantidade real / quantidade teórica) × 100. Pureza afeta o cálculo: a massa do reagente puro = massa total × (pureza/100). Combinar pureza e rendimento é comum em problemas industriais reais. No refino do petróleo brasileiro, cada etapa tem rendimento específico que deve ser calculado.',
    ['Um processo industrial com rendimento de 85% deve produzir 1000 kg de produto. Quantos kg de produto teórico serão gerados?', 'Se o minério de cobre tem 60% de pureza, quantas toneladas de minério são necessárias para obter 240 t de cobre puro?']),
  createLesson('g2-qui-b1-l7', 'L7: Estequiometria de Gases — Lei dos Gases Ideais', 'quimica',
    'A Lei dos Gases Ideais é PV = nRT, onde P é a pressão, V o volume, n o número de mols, R a constante dos gases (0,082 L·atm/mol·K) e T a temperatura em Kelvin. Permite calcular volumes de gases em quaisquer condições (não apenas CNTP). Gases reais desviam do comportamento ideal em alta pressão e baixa temperatura.',
    ['Qual o volume ocupado por 2 mols de CO₂ a 27°C e 2 atm?', 'Por que o CO₂ comporta-se mais como gás ideal em alta temperatura e baixa pressão?']),
  createLesson('g2-qui-b1-l8', 'L8: Leis dos Gases — Boyle, Charles e Gay-Lussac', 'quimica',
    'Lei de Boyle: P₁V₁ = P₂V₂ (temperatura constante — quanto maior a pressão, menor o volume). Lei de Charles: V₁/T₁ = V₂/T₂ (pressão constante — volume cresce com temperatura). Lei de Gay-Lussac: P₁/T₁ = P₂/T₂ (volume constante). Essas leis têm aplicações em pneumáticos, mergulho e meteorologia.',
    ['Uma bola de futebol está a 2 atm e 300 K. Se aquecida a 360 K (pressão constante), qual o novo volume relativo?', 'Por que os pneus de carros aumentam de pressão no verão?']),
  createLesson('g2-qui-b1-l9', 'L9: Misturas Gasosas — Pressão Parcial', 'quimica',
    'A Lei de Dalton das pressões parciais afirma que a pressão total de uma mistura de gases ideais é a soma das pressões parciais de cada componente. Pressão parcial de um gás = fração molar × pressão total. O ar atmosférico é uma mistura com N₂ (~78%), O₂ (~21%) e outros gases.',
    ['O ar tem pressão de 1 atm. Calcule a pressão parcial do O₂ (21%) e do N₂ (78%).', 'Por que mergulhadores respiram misturas especiais de gases e não apenas ar comprimido nas grandes profundidades?']),
  createLesson('g2-qui-b1-l10', 'L10: Diagrama de Fases e Ponto Triplo', 'quimica',
    'O diagrama de fases mostra em quais condições de pressão e temperatura uma substância existe como sólido, líquido ou gás. O ponto triplo é onde as três fases coexistem em equilíbrio. O ponto crítico é a temperatura e pressão acima das quais não existe distinção entre líquido e gás (fluido supercrítico — usado na extração de cafeína do café).',
    ['O que o diagrama de fases da água explica sobre o porquê do gelo flutuar na água líquida?', 'Como o CO₂ supercrítico é usado para extrair cafeína do café sem resíduos?']),
  createLesson('g2-qui-b1-l11', 'L11: Introdução às Soluções', 'quimica',
    'Uma solução é uma mistura homogênea de soluto (componente minoritário) em solvente (componente majoritário). As soluções podem ser gasosas (ar), líquidas (soro fisiológico, café) ou sólidas (ligas metálicas como o bronze). A solubilidade é a quantidade máxima de soluto que se dissolve em determinada quantidade de solvente.',
    ['Qual é o soluto e o solvente no soro fisiológico (NaCl em água)?', 'Por que algumas substâncias são solúveis em água e outras não, em termos de polaridade molecular?']),
  createLesson('g2-qui-b1-l12', 'L12: Concentração Comum (g/L)', 'quimica',
    'A concentração comum (C) expressa a massa de soluto em gramas por litro de solução: C = m(soluto) / V(solução). Essa é a concentração mais intuitiva e usada no cotidiano (soro fisiológico: 9 g/L de NaCl; soluções de limpeza). Não confundir volume da solução com volume do solvente.',
    ['Calcule a concentração em g/L de uma solução com 50g de NaOH em 500 mL de solução.', 'Por que é importante a concentração exata do soro fisiológico intravenoso?']),
  createLesson('g2-qui-b1-l13', 'L13: Concentração Molar (Molaridade)', 'quimica',
    'A molaridade (M) é o número de mols de soluto por litro de solução: M = n(soluto) / V(solução). É a concentração mais usada em laboratório. Para converter entre concentração comum e molaridade: M = C / M_molar. Soluções-padrão de molaridade conhecida são usadas em volumetria (titulação).',
    ['Calcule a molaridade de uma solução com 5,85g de NaCl em 250 mL de solução.', 'Por que a molaridade é mais útil que a concentração em g/L para cálculos estequiométricos em solução?']),
  createLesson('g2-qui-b1-l14', 'L14: Diluição de Soluções', 'quimica',
    'Na diluição, adiciona-se solvente a uma solução concentrada, reduzindo a concentração. A quantidade de soluto não muda: n₁ = n₂ → M₁V₁ = M₂V₂. Diluições em série são usadas em laboratório para obter concentrações muito baixas. A diluição de ácidos deve ser feita adicionando ácido à água (nunca o contrário!)',
    ['Quantos mL de solução de HCl 6M são necessários para preparar 500 mL de HCl 0,5M?', 'Por que ao diluir ácido sulfúrico concentrado deve-se adicionar o ácido à água e não o contrário?']),
  createLesson('g2-qui-b1-l15', 'L15: Mistura de Soluções', 'quimica',
    'Quando se misturam soluções do mesmo soluto, a quantidade total de soluto é a soma: n_total = n₁ + n₂. A molaridade resultante é M_res = n_total / V_total. Se as soluções têm solutos que reagem entre si (ex: ácido + base), calcula-se a estequiometria da reação antes de determinar a concentração final.',
    ['Misturando 200 mL de NaOH 2M com 300 mL de NaOH 1M, qual a molaridade da solução resultante?', 'O que acontece quando misturamos iguais volumes de HCl 1M e NaOH 1M?']),
  createLesson('g2-qui-b1-l16', 'L16: Propriedades Coligativas — Conceito', 'quimica',
    'Propriedades coligativas dependem apenas do número de partículas do soluto, não de sua natureza. São quatro: elevação do ponto de ebulição (ebulhoscopia), abaixamento do ponto de fusão (crioscopia), abaixamento da pressão de vapor (tonoscopia) e pressão osmótica (osmometria). Eletrólitos têm efeito maior por se dissociarem em íons.',
    ['Por que adicionar sal ao gelo o derrete mais rapidamente?', 'Por que colocamos sal na água ao cozinhar macarrão e como isso altera o ponto de ebulição?']),
  createLesson('g2-qui-b1-l17', 'L17: Osmose e Pressão Osmótica', 'quimica',
    'Osmose é o fluxo espontâneo de solvente através de uma membrana semipermeável, do lado menos concentrado para o mais concentrado. A pressão osmótica (π) impede esse fluxo: π = MRT. A osmose é crucial na biologia (transporte celular) e em tecnologia (osmose reversa para dessalinização — usada no Nordeste semiárido brasileiro).',
    ['Por que as células animais estouram em solução hipotônica e murcham em solução hipertônica?', 'Como funciona a dessalinização por osmose reversa e por que ela é importante para o Nordeste brasileiro?']),
  createLesson('g2-qui-b1-l18', 'L18: Revisão — Estequiometria Avançada e Soluções', 'quimica',
    'Os cálculos estequiométricos avançados (reagente limitante, rendimento, pureza) e os conceitos de solução (concentração, diluição, misturas, propriedades coligativas) são ferramentas fundamentais da Química analítica e industrial. Esses conceitos se aplicam em análises clínicas, controle de qualidade e produção farmacêutica.',
    ['Resuma os fatores que afetam o cálculo do rendimento de uma reação industrial.', 'Uma solução 0,1M de NaCl e outra 0,1M de glicose têm diferentes pressões osmóticas. Por quê?']),
];

export const quiLessonsB2: Lesson[] = [
  createLesson('g2-qui-b2-l1', 'L1: O Conceito de Solubilidade', 'quimica',
    'Solubilidade é a quantidade máxima de soluto que se dissolve em uma quantidade definida de solvente a dada temperatura. Soluções podem ser diluídas (abaixo do máximo), saturadas (no máximo) ou supersaturadas (instáveis, acima do máximo). Temperatura, pressão e natureza do soluto/solvente afetam a solubilidade.',
    ['Por que refrigerantes perdem o gás (CO₂) quando aquecidos?', 'O que acontece a uma solução supersaturada quando adicionamos um cristal do soluto?']),
  createLesson('g2-qui-b2-l2', 'L2: Fatores que Afetam a Solubilidade', 'quimica',
    'Para sólidos: a solubilidade geralmente aumenta com a temperatura. Para gases: a solubilidade aumenta com a pressão (Lei de Henry) e diminui com a temperatura (por isso refrigerantes gelados têm mais gás). A regra "semelhante dissolve semelhante" indica que solventes polares dissolvem solutos polares e iônicos.',
    ['Por que peixes morrem em água quente se oxigênio é menos solúvel em altas temperaturas?', 'Por que o óleo não se dissolve em água em termos de polaridade?']),
  createLesson('g2-qui-b2-l3', 'L3: Processo de Dissolução — Fatores Cinéticos', 'quimica',
    'A velocidade de dissolução (não a solubilidade) é influenciada por: agitação (aumenta o contato soluto-solvente), temperatura (aumenta a energia cinética das partículas) e grau de divisão do soluto (superfície de contato maior). Por isso sal fino dissolve mais rápido que sal grosso no mesmo volume de água.',
    ['Por que açúcar em pó dissolve mais rápido que açúcar cristal na mesma temperatura?', 'Quais são as diferenças entre velocidade de dissolução e solubilidade?']),
  createLesson('g2-qui-b2-l4', 'L4: Concentração Percentual em Massa', 'quimica',
    'A concentração em porcentagem em massa (% m/m) é: % = (massa do soluto / massa da solução) × 100. É muito usada no rótulo de produtos: álcool 70% significa 70g de etanol por 100g de solução. A densidade da solução permite converter entre % m/m e concentração em g/L ou molaridade.',
    ['Uma solução de NaOH tem concentração de 40% (m/m) e densidade 1,4 g/mL. Calcule a molaridade.', 'Por que o álcool gel 70% é mais eficaz contra vírus do que o álcool 96%?']),
  createLesson('g2-qui-b2-l5', 'L5: Fração Molar e Molalidade', 'quimica',
    'Fração molar (X) = mols do componente / mols totais. A soma de todas as frações molares = 1. Molalidade (m) = mols de soluto / kg de solvente. A molalidade não varia com a temperatura (ao contrário da molaridade), sendo preferida para propriedades coligativas. Essas grandezas são usadas em cálculos termodinâmicos avançados.',
    ['Calcule a fração molar do etanol em uma solução com 46g de etanol (M=46) em 180g de água.', 'Por que a molalidade é preferida para cálculos de propriedades coligativas?']),
  createLesson('g2-qui-b2-l6', 'L6: Coloides e Suspensões', 'quimica',
    'Coloides têm partículas entre 1 e 1000 nm dispersas em outro meio. Diferentemente das soluções, não passam em membranas de diálise e exibem o Efeito Tyndall (dispersão de luz). Exemplos: leite, sangue, fumaça, gelatina. Suspensões têm partículas maiores (> 1000 nm), sedimentam por repouso: ex: areia em água.',
    ['Como o Efeito Tyndall diferencia um coloide de uma solução verdadeira?', 'Por que o leite, sendo branco, é classificado como coloide e não como solução?']),
  createLesson('g2-qui-b2-l7', 'L7: Titulação Ácido-Base (Volumetria)', 'quimica',
    'A titulação é uma técnica analítica para determinar a concentração de uma solução a partir de outra de concentração conhecida (solução-padrão). O ponto de equivalência é quando a reação se completa. O ponto final é indicado pelo indicador ácido-base (ex: fenolftaleína). Usa-se a relação: n(ácido) × a = n(base) × b.',
    ['Numa titulação, 25 mL de NaOH 0,1M neutralizam 20 mL de HCl. Qual a concentração do HCl?', 'Por que é importante calibrar a bureta antes de uma titulação?']),
  createLesson('g2-qui-b2-l8', 'L8: Análise de Alimentos por Titulação', 'quimica',
    'A titulação é usada para controle de qualidade de alimentos. A acidez do leite (por titulação com NaOH) indica se está fermentado. A acidez de óleos e vinagres também é determinada por titulação. Essa análise é obrigatória na indústria alimentícia brasileira conforme normas do MAPA e da ANVISA.',
    ['Como a acidez do leite é determinada por titulação e o que isso indica sobre sua qualidade?', 'Por que o vinagre tem graduação de acidez no rótulo e como ela é medida?']),
  createLesson('g2-qui-b2-l9', 'L9: Termoquímica — Conceitos Fundamentais', 'quimica',
    'Termoquímica estuda a troca de calor nas reações químicas. Entalpia (ΔH) é o calor trocado a pressão constante. ΔH < 0: reação exotérmica (libera calor, ex: combustão). ΔH > 0: reação endotérmica (absorve calor, ex: fotossíntese). O estado de referência (padrão) é 25°C e 1 atm.',
    ['Por que queimadas são preocupantes do ponto de vista da termoquímica e do clima?', 'Identifique se a dissolução do NaOH em água (que aquece o recipiente) é exo ou endotérmica.']),
  createLesson('g2-qui-b2-l10', 'L10: Entalpia de Formação e Combustão', 'quimica',
    'Entalpia padrão de formação (ΔHf°) é o ΔH para formar 1 mol de substância a partir dos elementos no estado padrão. Entalpia de combustão (ΔHc°) é o ΔH para a combustão completa de 1 mol da substância. O etanol tem ΔHc° ≈ -1366 kJ/mol, sendo um biocombustível com alto poder calorífico.',
    ['O que é entalpia padrão de formação e por que os elementos no estado padrão têm ΔHf° = 0?', 'Compare as entalpias de combustão do etanol e da gasolina e discuta a eficiência energética de cada combustível.']),
  createLesson('g2-qui-b2-l11', 'L11: Lei de Hess', 'quimica',
    'A Lei de Hess estabelece que a variação de entalpia de uma reação é a mesma independentemente do caminho seguido (estado inicial e final determinam ΔH). Permite calcular ΔH de reações difíceis de medir diretamente somando equações e seus ΔH. É análoga ao conceito de função de estado em termodinâmica.',
    ['Usando a Lei de Hess, calcule o ΔH para: C(s) + ½O₂(g) → CO(g), dados ΔHf do CO₂ e ΔHc do CO.', 'Por que a Lei de Hess é tão útil para reações que não podem ser medidas diretamente no laboratório?']),
  createLesson('g2-qui-b2-l12', 'L12: Energia de Ligação', 'quimica',
    'A energia de ligação é a energia necessária para romper 1 mol de uma ligação covalente no estado gasoso. A entalpias de reação pode ser estimada por: ΔH ≈ Σ(energias de ligação dos reagentes) − Σ(energias de ligação dos produtos). Ligações duplas e triplas têm maior energia que ligações simples.',
    ['Por que a combustão de compostos com ligações C-H libera tanta energia?', 'O que o valor da energia de ligação do N≡N (946 kJ/mol) revela sobre a estabilidade do N₂?']),
  createLesson('g2-qui-b2-l13', 'L13: Cinética Química — Velocidade de Reação', 'quimica',
    'A cinética química estuda a velocidade das reações químicas. Velocidade média = variação de concentração / intervalo de tempo. Para os reagentes, a velocidade é negativa (concentração diminui); para produtos, é positiva. A velocidade não é constante durante a reação, diminuindo à medida que os reagentes se esgotam.',
    ['Por que a velocidade de uma reação diminui ao longo do tempo?', 'Como você mediria experimentalmente a velocidade de formação de gás CO₂ na reação de mármore com HCl?']),
  createLesson('g2-qui-b2-l14', 'L14: Fatores que Afetam a Velocidade das Reações', 'quimica',
    'Quatro fatores principais afetam a velocidade: concentração (maior concentração = mais colisões efetivas), temperatura (cada 10°C de aumento aproximadamente dobra a velocidade — regra de Van\'t Hoff), superfície de contato (sólidos triturados reagem mais rápido) e catalisador (fornece caminho alternativo com menor energia de ativação).',
    ['Por que alimentos estragam mais rapidamente no verão do que no inverno?', 'Por que um catalisador acelera a reação mas não aparece no balanço final da equação?']),
  createLesson('g2-qui-b2-l15', 'L15: Teoria das Colisões e Energia de Ativação', 'quimica',
    'Para que uma reação ocorra, as moléculas devem colidir com energia suficiente (energia de ativação, Ea) e orientação correta. O diagrama de energia mostra o perfil da reação: energia dos reagentes, barreira de ativação e energia dos produtos. Catalisadores diminuem a Ea sem alterar o ΔH da reação.',
    ['O que é energia de ativação e como os catalisadores a afetam?', 'Por que nem todas as colisões entre moléculas resultam em reação química?']),
  createLesson('g2-qui-b2-l16', 'L16: Lei da Velocidade e Ordem de Reação', 'quimica',
    'A lei da velocidade relaciona a velocidade com as concentrações dos reagentes: v = k[A]ⁿ[B]ᵐ, onde k é a constante de velocidade e n, m são as ordens de reação. A ordem total é n+m. A ordem não é deduzida dos coeficientes, mas determinada experimentalmente. A constante k depende apenas da temperatura.',
    ['Uma reação é de 1ª ordem em A e 2ª ordem em B. Se dobrarmos [B], como a velocidade se altera?', 'Por que a ordem de reação não pode ser determinada apenas olhando a equação balanceada?']),
  createLesson('g2-qui-b2-l17', 'L17: Catálise — Tipos e Aplicações Industriais', 'quimica',
    'Catálise homogênea: catalisador no mesmo estado físico que os reagentes. Catálise heterogênea: estados físicos diferentes (ex: Pt sólida em reações gasosas — catalisador nos conversores catalíticos de automóveis). Enzimas são catalisadores biológicos (catalase decompõe H₂O₂ em células). O Processo Haber usa catalisador de Fe para produzir amônia.',
    ['Como funciona o catalisador conversor nos escapamentos dos carros para reduzir a poluição?', 'Por que as enzimas são tão específicas e eficientes como catalisadores biológicos?']),
  createLesson('g2-qui-b2-l18', 'L18: Revisão — Termoquímica e Cinética', 'quimica',
    'Termoquímica e cinética são fundamentais para compreender como e com que velocidade as reações ocorrem. A entalpias de reação determina se a reação é espontânea do ponto de vista energético. A cinética determina se a reação é rápida o suficiente para ter aplicação prática. Combustíveis, alimentos e catalisadores conectam esses temas ao cotidiano.',
    ['Qual a diferença entre termodinâmica (ΔH) e cinética (velocidade) de uma reação?', 'Cite um exemplo industrial em que tanto o controle de temperatura quanto o uso de catalisadores são essenciais.']),
];

export const quiLessonsB3: Lesson[] = [
  createLesson('g2-qui-b3-l1', 'L1: Equilíbrio Químico — Conceito e Características', 'quimica',
    'O equilíbrio químico é um estado dinâmico em que as velocidades das reações direta (formação de produtos) e inversa (formação de reagentes) são iguais. As concentrações de reagentes e produtos permanecem constantes, mas não necessariamente iguais. É representado por setas duplas (⇌) na equação.',
    ['Por que o equilíbrio químico é considerado "dinâmico" e não estático?', 'Cite um equilíbrio químico que ocorre no corpo humano (dica: transporte de oxigênio pelo sangue).']),
  createLesson('g2-qui-b3-l2', 'L2: Constante de Equilíbrio (Kc e Kp)', 'quimica',
    'Para a reação aA + bB ⇌ cC + dD, a constante Kc = [C]ᶜ[D]ᵈ / [A]ᵃ[B]ᵇ. Sólidos e líquidos puros não aparecem na expressão de Kc. Kp usa pressões parciais em vez de concentrações. Se K > 1, o equilíbrio favorece produtos; se K < 1, favorece reagentes. K depende apenas da temperatura.',
    ['Escreva a expressão de Kc para: N₂(g) + 3H₂(g) ⇌ 2NH₃(g).', 'Por que sólidos não aparecem na expressão da constante de equilíbrio?']),
  createLesson('g2-qui-b3-l3', 'L3: Princípio de Le Chatelier', 'quimica',
    'Le Chatelier: quando um sistema em equilíbrio sofre uma perturbação (variação de concentração, temperatura ou pressão), o equilíbrio se desloca no sentido de minimizar essa perturbação. Adicionar reagente: equilíbrio desloca para produtos. Aumentar pressão (gases): equilíbrio desloca para o lado de menor número de mols gasosos.',
    ['No equilíbrio N₂ + 3H₂ ⇌ 2NH₃ (ΔH < 0), o que acontece se aumentarmos a temperatura?', 'Como o princípio de Le Chatelier explica a produção industrial de amônia a alta pressão?']),
  createLesson('g2-qui-b3-l4', 'L4: Equilíbrio Ácido-Base em Solução', 'quimica',
    'Ácidos e bases fracas estabelecem equilíbrios em solução. Para ácidos fracos HA ⇌ H⁺ + A⁻: Ka = [H⁺][A⁻]/[HA]. Para bases fracas BOH ⇌ B⁺ + OH⁻: Kb = [B⁺][OH⁻]/[BOH]. O grau de ionização (α) indica a fração ionizada. Ácido forte: α ≈ 100%. Ácido fraco: α << 100%.',
    ['Por que o ácido acético (Ka = 1,8×10⁻⁵) é considerado ácido fraco?', 'Como calcular o pH de uma solução 0,1M de CH₃COOH dado Ka = 1,8×10⁻⁵?']),
  createLesson('g2-qui-b3-l5', 'L5: Produto Iônico da Água (Kw)', 'quimica',
    'A água se autoioniza: H₂O ⇌ H⁺ + OH⁻. O produto iônico Kw = [H⁺][OH⁻] = 10⁻¹⁴ a 25°C. Em solução ácida: [H⁺] > 10⁻⁷ M (pH < 7). Em solução básica: [OH⁻] > 10⁻⁷ M (pH > 7). O Kw aumenta com a temperatura, explicando por que a água pura em altas temperaturas tem pH < 7 sem ser ácida quimicamente.',
    ['Calcule o [OH⁻] de uma solução com [H⁺] = 10⁻³ M. A solução é ácida, neutra ou básica?', 'Por que o pH da água pura a 37°C (temperatura corporal) é ligeiramente menor que 7?']),
  createLesson('g2-qui-b3-l6', 'L6: Cálculo de pH e pOH', 'quimica',
    'pH = -log[H⁺] e pOH = -log[OH⁻]. pH + pOH = 14 (a 25°C). Para ácidos fortes monopróticos: [H⁺] = molaridade do ácido. Para bases fortes: [OH⁻] = molaridade × número de OH⁻. Para ácidos/bases fracos, usa-se Ka ou Kb para calcular [H⁺] ou [OH⁻] via fórmula aproximada: [H⁺] = √(Ka × C).',
    ['Calcule o pH de 0,01M de HCl (ácido forte).', 'Calcule o pH de uma solução 0,1M de NH₃ (Kb = 1,8×10⁻⁵).']),
  createLesson('g2-qui-b3-l7', 'L7: Hidrólise Salina', 'quimica',
    'Sais dissolvidos em água podem alterar o pH: sal de ácido fraco + base forte → solução básica (ex: CH₃COONa). Sal de ácido forte + base fraca → solução ácida (ex: NH₄Cl). Sal de ácido forte + base forte → solução neutra (ex: NaCl). Isso é crucial na análise de fertilizantes e no pH de solos agrícolas.',
    ['Por que uma solução de acetato de sódio (CH₃COONa) é básica?', 'Como o uso de fertilizantes amoniacais (NH₄⁺) pode acidificar o solo ao longo do tempo?']),
  createLesson('g2-qui-b3-l8', 'L8: Soluções Tampão — Cálculo de pH', 'quimica',
    'A equação de Henderson-Hasselbalch calcula o pH de soluções tampão: pH = pKa + log([A⁻]/[HA]). O pH do tampão varia pouco ao adicionar ácido ou base por consumo do componente ativo. O poder tampão é máximo quando [A⁻] = [HA] (pH = pKa). Tampões biológicos são essenciais para manter o pH do sangue e das células.',
    ['Calcule o pH de um tampão com 0,1M de CH₃COOH e 0,1M de CH₃COONa (pKa = 4,74).', 'Por que o tampão fosfato é usado em laboratórios de biologia molecular?']),
  createLesson('g2-qui-b3-l9', 'L9: Equilíbrio de Solubilidade — Kps', 'quimica',
    'O produto de solubilidade (Kps) é a constante de equilíbrio para a dissolução de um sal pouco solúvel: para BaSO₄(s) ⇌ Ba²⁺(aq) + SO₄²⁻(aq), Kps = [Ba²⁺][SO₄²⁻]. Quanto menor o Kps, menos solúvel o composto. O efeito do íon comum diminui a solubilidade de um sal pouco solúvel.',
    ['Como o Kps pode prever se um precipitado se forma ao misturar duas soluções?', 'Por que adicionar NaCl a uma solução saturada de AgCl diminui ainda mais a solubilidade do AgCl?']),
  createLesson('g2-qui-b3-l10', 'L10: Equilíbrio em Sistemas Industriais', 'quimica',
    'A síntese industrial da amônia (Processo Haber) usa as condições ótimas de acordo com Le Chatelier: alta pressão (favorece o lado de 2 mols de gás), temperatura moderada (equilíbrio favorecer produtos, mas cinética ser razoável) e catalisador de Fe. A amônia é a base dos fertilizantes nitrogenados que sustentam a agricultura mundial.',
    ['Por que a temperatura de 450°C é um compromisso entre termodinâmica e cinética no Processo Haber?', 'Quais as consequências para a segurança alimentar mundial se parássemos de produzir amônia pelo Processo Haber?']),
  createLesson('g2-qui-b3-l11', 'L11: Equilíbrio e Pilhas Químicas', 'quimica',
    'Pilhas e baterias são dispositivos que convertem energia química em elétrica via reações redox. A força eletromotriz (fem) ou ddp é proporcional à variação de energia de Gibbs (ΔG = -nFE). No equilíbrio, E = 0 e ΔG = 0 (bateria descarregada). Baterias de íon-lítio (usadas em celulares e carros elétricos) são sistemas de equilíbrio eletroquímico.',
    ['Por que uma bateria "morre" ao ser completamente descarregada, em termos de equilíbrio químico?', 'Como o desenvolvimento de baterias de maior capacidade impacta a transição energética no Brasil?']),
  createLesson('g2-qui-b3-l12', 'L12: Equilíbrio e Pressão de Vapor', 'quimica',
    'Num recipiente fechado, o líquido evapora até que a pressão de vapor de equilíbrio seja atingida. Nesse estado, a taxa de evaporação = taxa de condensação. A pressão de vapor aumenta com a temperatura. Solutos não voláteis diminuem a pressão de vapor do solvente (Lei de Raoult), explicando o abaixamento crioscópico e elevação ebulioscópica.',
    ['Por que a pressão de vapor da água salina é menor que a da água pura?', 'Como o Diagrama de Fase usa o conceito de pressão de vapor para prever os estados da água?']),
  createLesson('g2-qui-b3-l13', 'L13: Equilíbrio em Sistemas Biológicos', 'quimica',
    'O corpo humano mantém vários equilíbrios: pH do sangue (7,35-7,45), oxigenação (HbO₂ ⇌ Hb + O₂), CO₂ (CO₂ + H₂O ⇌ H₂CO₃ ⇌ H⁺ + HCO₃⁻). Medicamentos podem deslocar esses equilíbrios: antiácidos neutralizam H⁺, oxigênio puro desloca o equilíbrio da hemoglobina. Desequilíbrios causam acidose ou alcalose.',
    ['Como o bicarbonato no sangue funciona como tampão para manter o pH?', 'Por que atletas em altitude têm mais glóbulos vermelhos e como isso se relaciona ao equilíbrio hemoglobina-oxigênio?']),
  createLesson('g2-qui-b3-l14', 'L14: Grau de Ionização e pH de Ácidos Fracos', 'quimica',
    'O grau de ionização (α) de um ácido fraco é a fração que se ioniza: α = [H⁺]/C₀. Para α pequeno (< 5%): [H⁺] ≈ √(Ka × C₀). Para α maior, usa-se a equação quadrática. Quanto maior a diluição, maior o grau de ionização (Lei de Ostwald). Esse conceito é fundamental para entender tampões biológicos.',
    ['Calcule o grau de ionização do ácido acético 0,1M (Ka = 1,8×10⁻⁵).', 'Por que diluir um ácido fraco aumenta seu grau de ionização mas diminui o número total de íons H⁺?']),
  createLesson('g2-qui-b3-l15', 'L15: Análise Instrumental — Espectrofotometria', 'quimica',
    'A espectrofotometria mede a absorção de luz por substâncias em solução. A Lei de Beer-Lambert: A = εCl (A = absorbância, ε = coeficiente de extinção molar, C = concentração, l = comprimento do caminho). É usada para determinar concentrações de substâncias coloridas em análises clínicas, ambientais e de alimentos.',
    ['Como a espectrofotometria é usada para medir a concentração de glicose no sangue?', 'Por que a lei de Beer-Lambert falha em concentrações muito altas?']),
  createLesson('g2-qui-b3-l16', 'L16: Cromatografia Analítica', 'quimica',
    'A cromatografia separa misturas com base nas diferentes afinidades dos componentes por uma fase estacionária e uma fase móvel. HPLC (cromatografia líquida de alta eficiência) é usada para controle de qualidade de medicamentos. CG (cromatografia gasosa) detecta agrotóxicos em alimentos. Essas técnicas são obrigatórias na vigilância sanitária brasileira.',
    ['Como a cromatografia gasosa detecta resíduos de agrotóxicos em frutas e vegetais?', 'Por que o HPLC é preferido para análise de princípios ativos em medicamentos?']),
  createLesson('g2-qui-b3-l17', 'L17: Equilíbrio e Qualidade da Água', 'quimica',
    'O pH da água tratada (6,5–8,5) é mantido por equilíbrios entre CO₂/HCO₃⁻/CO₃²⁻. O cloro (desinfetante) existe em equilíbrio com ácido hipocloroso (HOCl): Cl₂ + H₂O ⇌ HOCl + HCl. Flúor é adicionado para prevenção de cáries. O tratamento de esgoto usa reações de precipitação e oxidação para remover poluentes.',
    ['Por que o pH da água de abastecimento deve ser mantido levemente básico?', 'Como o equilíbrio cloro/ácido hipocloroso explica a eficácia do cloro como desinfetante?']),
  createLesson('g2-qui-b3-l18', 'L18: Revisão — Equilíbrio Químico', 'quimica',
    'O equilíbrio químico permeia toda a Química e a Biologia: ácido-base, solubilidade, fases, e sistemas industriais. O princípio de Le Chatelier é a chave para prever como sistemas em equilíbrio respondem a perturbações. Dominar esses conceitos é fundamental para entender desde reações industriais até funções biológicas vitais.',
    ['Explique como o princípio de Le Chatelier se aplica ao equilíbrio CO₂ + H₂O ⇌ H₂CO₃ durante o exercício físico.', 'Quais os fatores que determinam se a constante de equilíbrio de uma reação é maior ou menor que 1?']),
];

export const quiLessonsB4: Lesson[] = [
  createLesson('g2-qui-b4-l1', 'L1: Eletroquímica — Oxidação e Redução', 'quimica',
    'Reações eletroquímicas envolvem transferência de elétrons. Oxidação: perda de elétrons (aumento do NOX). Redução: ganho de elétrons (diminuição do NOX). O agente oxidante é reduzido e o agente redutor é oxidado. A série eletroquímica (série de reatividade) ordena os metais pela facilidade de oxidação.',
    ['O que acontece com o alumínio quando ele reage com uma solução de CuSO₄?', 'Por que metais mais reativos (como Fe) são usados como ânodo sacrificial para proteger outros metais?']),
  createLesson('g2-qui-b4-l2', 'L2: Pilhas e Baterias — Princípios', 'quimica',
    'Uma pilha galvânica converte energia química em elétrica. O eletrodo negativo (ânodo) sofre oxidação e libera elétrons. O eletrodo positivo (cátodo) recebe elétrons e sofre redução. Os elétrons fluem pelo circuito externo e os íons se movem pela ponte salina para manter a neutralidade elétrica.',
    ['Na pilha de Daniell (Zn/Cu), escreva as semi-reações do ânodo e do cátodo.', 'Por que a ponte salina é essencial para o funcionamento de uma pilha galvânica?']),
  createLesson('g2-qui-b4-l3', 'L3: Força Eletromotriz (FEM) e Potencial de Eletrodo', 'quimica',
    'O potencial de redução padrão (E°red) de cada eletrodo é medido em relação ao eletrodo padrão de hidrogênio (E° = 0V). A FEM da pilha é E°pilha = E°cátodo − E°ânodo. Se E° > 0, a reação é espontânea. A FEM se relaciona à energia livre: ΔG° = −nFE°.',
    ['Uma pilha tem E°cátodo = +0,34V (Cu²⁺/Cu) e E°ânodo = −0,76V (Zn²⁺/Zn). Calcule a FEM.', 'Por que uma reação com ΔG° negativo corresponde a uma FEM positiva?']),
  createLesson('g2-qui-b4-l4', 'L4: Eletrólise — Fundamentos', 'quimica',
    'A eletrólise usa energia elétrica para forçar reações não-espontâneas. O ânodo (eletrodo + conectado à fonte) sofre oxidação; o cátodo (eletrodo −) sofre redução. A eletrólise da água produz H₂ (cátodo) e O₂ (ânodo). No Brasil, a eletrólise é usada para produzir alumínio (maior produtor mundial de Al a partir de bauxita amazônica).',
    ['Por que a produção de alumínio por eletrólise consome tanta energia elétrica?', 'Quais as aplicações da eletrólise na indústria química brasileira?']),
  createLesson('g2-qui-b4-l5', 'L5: Galvanoplastia e Eletrodeposição', 'quimica',
    'A galvanoplastia deposita uma camada metálica sobre um objeto pela eletrólise. O objeto a ser revestido é o cátodo; o metal de revestimento (fonte) é o ânodo. É usada para cromagem de peças automotivas, prateação de talheres e niquelamento. No Brasil, é amplamente usada na indústria de autopeças.',
    ['Como funciona o processo de cromagem de uma peça de automóvel?', 'Quais os riscos ambientais do descarte incorreto de efluentes de galvanoplastia?']),
  createLesson('g2-qui-b4-l6', 'L6: Corrosão de Metais', 'quimica',
    'Corrosão é a oxidação espontânea de metais por agentes oxidantes do ambiente (O₂, H₂O, ácidos). A ferrugem é a oxidação do ferro: 4Fe + 3O₂ + nH₂O → 2Fe₂O₃·nH₂O. A corrosão eletroquímica ocorre quando dois metais diferentes em contato formam uma pilha espontânea. Prejuízo anual com corrosão no Brasil é de bilhões de reais.',
    ['Por que a corrosão é mais intensa em regiões litorâneas e úmidas?', 'Quais métodos de proteção anticorrosiva são usados na indústria do petróleo offshore?']),
  createLesson('g2-qui-b4-l7', 'L7: Proteção Anticorrosiva', 'quimica',
    'Métodos de proteção: pintura (barreira física), galvanização (zinco protege o aço por ser mais reativo), anodização (camada de óxido de Al), cátodo de sacrifício (zinco ou magnésio conectado ao metal a proteger — perde-se o cátodo, mas salva-se a estrutura principal). Oleodutos da Petrobras usam corrente catódica impressa.',
    ['Como o processo de galvanização protege o aço da corrosão?', 'Por que ligas como o aço inoxidável (Fe+Cr+Ni) são mais resistentes à corrosão do que o ferro puro?']),
  createLesson('g2-qui-b4-l8', 'L8: Leis de Faraday para Eletrólise', 'quimica',
    '1ª Lei de Faraday: a massa depositada é proporcional à carga elétrica (Q = i × t). 2ª Lei: massas de diferentes substâncias depositadas pela mesma carga são proporcionais às suas massas equivalentes. Cálculo: m = (M × i × t) / (n × F), onde F = 96.500 C/mol. Usado para calcular tempo e corrente em processos industriais.',
    ['Calcule a massa de Cu depositada ao passar 2A por 30 minutos numa solução de CuSO₄.', 'Como as leis de Faraday são usadas para controlar a espessura da camada em galvanoplastia?']),
  createLesson('g2-qui-b4-l9', 'L9: Baterias Modernas — Lítio e Sustentabilidade', 'quimica',
    'Baterias de íon-lítio (Li-ion) têm alta densidade de energia e são recarregáveis. Usadas em celulares, laptops e veículos elétricos. O Brasil possui grandes reservas de lítio no Minas Gerais. Baterias de estado sólido prometem ser mais seguras e eficientes. A reciclagem de baterias é um desafio ambiental e econômico crescente.',
    ['Por que o lítio é o metal preferido para baterias de alta performance?', 'Quais os impactos ambientais da mineração de lítio e como o Brasil pode produzir lítio de forma mais sustentável?']),
  createLesson('g2-qui-b4-l10', 'L10: Hidrogênio Verde — O Combustível do Futuro', 'quimica',
    'O hidrogênio verde é produzido por eletrólise da água usando energia elétrica renovável (solar ou eólica). É um combustível limpo: sua combustão produz apenas água. Células de combustível (H₂ + O₂ → H₂O + eletricidade) são mais eficientes que motores de combustão. O Brasil tem grande potencial para produção de H₂ verde no Nordeste.',
    ['Por que o hidrogênio produzido por eletrólise com energia solar é chamado de "hidrogênio verde"?', 'Quais as principais barreiras técnicas e econômicas para a adoção em larga escala do hidrogênio verde?']),
  createLesson('g2-qui-b4-l11', 'L11: Química Orgânica — Introdução ao Carbono', 'quimica',
    'A Química Orgânica estuda os compostos de carbono. O C é único: forma 4 ligações covalentes, pode fazer cadeias longas, ramificadas ou cíclicas, e ligar-se a H, O, N, S, P e halogênios. A imensa diversidade dos compostos orgânicos (>20 milhões) é possível graças à capacidade do C de fazer ligações C-C simples, duplas e triplas.',
    ['Por que o carbono é capaz de formar mais compostos que qualquer outro elemento?', 'Qual a importância dos compostos orgânicos para a vida: proteínas, DNA, lipídios são todos orgânicos.']),
  createLesson('g2-qui-b4-l12', 'L12: Hidrocarbonetos — Alcanos', 'quimica',
    'Alcanos (parafinas) têm apenas ligações C-C simples (saturados). Fórmula geral: CₙH₂ₙ₊₂. Nomenclatura: met-, et-, prop-, but-, pent-, hex- + -ano. São encontrados no petróleo (fonte principal de alcanos no Brasil). São pouco reativos quimicamente mas combustíveis importantes (gás natural: metano CH₄, GLP: propano + butano).',
    ['Escreva as fórmulas estruturais do metano (CH₄), etano (C₂H₆) e propano (C₃H₈).', 'Por que o GLP (gás de cozinha) é mais pesado que o ar e deve ser armazenado em locais ventilados?']),
  createLesson('g2-qui-b4-l13', 'L13: Hidrocarbonetos — Alcenos e Alcinos', 'quimica',
    'Alcenos têm uma ligação C=C dupla (fórmula: CₙH₂ₙ). Alcinos têm uma ligação C≡C tripla (fórmula: CₙH₂ₙ₋₂). São insaturados e mais reativos. O etileno (eteno: CH₂=CH₂) é o hidrocarboneto industrial mais produzido: base para polietileno (PE), plástico mais usado no mundo. O acetileno (etino: HC≡CH) é usado em maçarico.',
    ['Por que alcenos são mais reativos que alcanos?', 'Como o etileno é produzido pela indústria petroquímica brasileira e quais seus principais derivados?']),
  createLesson('g2-qui-b4-l14', 'L14: Isomeria — Conceito e Tipos', 'quimica',
    'Isômeros têm mesma fórmula molecular mas estruturas diferentes, resultando em propriedades distintas. Isomeria plana: de cadeia (carbono muda de posição na cadeia), de posição (insaturação ou grupo funcional muda de posição), de função (grupos funcionais diferentes). Isomeria espacial: geométrica (cis/trans) e óptica (quiralidade, enantiômeros).',
    ['O butano (C₄H₁₀) tem dois isômeros de cadeia. Escreva suas estruturas.', 'Por que enantiômeros (isômeros ópticos) têm comportamentos diferentes em sistemas biológicos, como medicamentos?']),
  createLesson('g2-qui-b4-l15', 'L15: Aromáticos — Benzeno e Derivados', 'quimica',
    'O benzeno (C₆H₆) é o hidrocarboneto aromático mais simples, com anel de 6 carbonos e elétrons deslocalizados. É extremamente estável e cancerígeno. Derivados importantes: tolueno (solvente), estireno (poliestireno), fenol (desinfetante), anilina (corantes). São obtidos do petróleo e carvão mineral no Brasil.',
    ['O que é deslocalização eletrônica e por que ela torna o benzeno tão estável?', 'Por que o benzeno é cancerígeno e como a regulação do seu uso é feita no Brasil?']),
  createLesson('g2-qui-b4-l16', 'L16: Polímeros — Adição e Condensação', 'quimica',
    'Polímeros são macromoléculas formadas pela repetição de unidades chamadas monômeros. Polímeros de adição: monômeros com ligações duplas se unem sem perda de átomos (PE, PP, PVC, poliestireno). Polímeros de condensação: reação entre dois tipos de monômero com liberação de pequenas moléculas como água (nylon, poliéster, Biopol).',
    ['Qual o monômero do polietileno (PE) e como se forma o polímero?', 'Por que os bioplásticos (produzidos a partir de cana-de-açúcar no Brasil) são mais sustentáveis que os plásticos convencionais?']),
  createLesson('g2-qui-b4-l17', 'L17: Plásticos, Reciclagem e Impacto Ambiental', 'quimica',
    'O Brasil produz milhões de toneladas de plástico por ano. A reciclagem mecânica (trituração e refusão) é o método mais comum, mas limitada por contaminação. Reciclagem química (pirólise) converte plástico em combustível. Plásticos biodegradáveis e bioplásticos são alternativas. Microplásticos são encontrados em rios, oceanos e até no sangue humano.',
    ['Quais são os 7 tipos de plástico indicados nos códigos de reciclagem e quais as limitações de reciclagem de cada um?', 'Quais os impactos dos microplásticos no ecossistema dos rios do Tocantins?']),
  createLesson('g2-qui-b4-l18', 'L18: Revisão — Eletroquímica e Introdução à Química Orgânica', 'quimica',
    'Eletroquímica (pilhas, eletrólise, corrosão) e Química Orgânica (hidrocarbonetos, polímeros) são as grandes áreas da 2ª série. A eletroquímica tem aplicações diretas em energia limpa (H₂ verde, baterias) e proteção de infraestrutura. A química orgânica explica os materiais do cotidiano, combustíveis e a base da vida.',
    ['Como a eletroquímica e a química orgânica se conectam no conceito de combustível? Cite exemplos.', 'Qual a importância do setor petroquímico brasileiro para a economia e quais os desafios de sua transição para fontes renováveis?']),
];
