
import { Lesson } from './types';
import { createLesson } from './data_helpers';

// Biologia 1ª Série: 18 aulas por bimestre (Total 72)
export const bioLessonsB1: Lesson[] = [
  createLesson('g1-bio-b1-l1', 'L1: O que é Biologia e a Origem da Vida', 'biologia',
    'Biologia é a ciência que estuda os seres vivos e suas relações com o ambiente. A teoria mais aceita para a origem da vida é a Abiogênese Moderna (Oparin-Haldane): na Terra primitiva, moléculas inorgânicas simples se combinaram para formar moléculas orgânicas, depois protocélulas e, por fim, as primeiras células há ~3,8 bilhões de anos.',
    ['Qual a diferença entre a hipótese da biogênese e da abiogênese e como Pasteur resolveu essa controvérsia?', 'Por que o experimento de Urey-Miller foi importante para entender a origem da vida na Terra?']),
  createLesson('g1-bio-b1-l2', 'L2: Características dos Seres Vivos', 'biologia',
    'Todos os seres vivos compartilham características: organização celular, metabolismo (reações químicas que sustentam a vida), crescimento e desenvolvimento, reprodução, resposta ao ambiente (irritabilidade) e homeostase (equilíbrio interno). Vírus não são considerados seres vivos porque dependem de células para se reproduzir.',
    ['Por que os vírus não são classificados como seres vivos pelos biólogos?', 'Como a homeostase permite que o corpo humano mantenha temperatura constante mesmo em ambientes frios?']),
  createLesson('g1-bio-b1-l3', 'L3: A Célula — Unidade da Vida', 'biologia',
    'A Teoria Celular (Schleiden, Schwann, Virchow — séc. XIX) afirma que: toda célula vem de uma célula pré-existente; a célula é a unidade básica da vida; todo organismo é composto de células. Células procarióticas (bactérias e arqueas) não têm núcleo organizado. Células eucarióticas (animais, vegetais, fungos, protistas) têm núcleo com membrana.',
    ['Qual a principal diferença entre células procarióticas e eucarióticas?', 'Por que a Teoria Celular é considerada uma das maiores conquistas da Biologia?']),
  createLesson('g1-bio-b1-l4', 'L4: Membrana Plasmática — Estrutura e Função', 'biologia',
    'A membrana plasmática é formada por um bicamada de fosfolipídios com proteínas inseridas (modelo do mosaico fluido — Singer e Nicolson, 1972). É semipermeável: controla o que entra e sai da célula. As proteínas podem ser receptoras, transportadoras, de sinalização ou estruturais. A membrana é dinâmica — seus componentes se movem.',
    ['Por que a membrana plasmática é chamada de "semipermeável"?', 'Como os receptores da membrana plasmática permitem que as células se comuniquem com o ambiente?']),
  createLesson('g1-bio-b1-l5', 'L5: Transporte pela Membrana — Passivo e Ativo', 'biologia',
    'Transporte passivo: ocorre a favor do gradiente de concentração, sem gasto de energia. Difusão simples (O₂ e CO₂ atravessam a bicamada), difusão facilitada (glicose e íons, por proteínas canal) e osmose (água, de menor para maior concentração de soluto). Transporte ativo: contra o gradiente, com gasto de ATP — ex: Bomba de Sódio-Potássio (Na⁺/K⁺-ATPase).',
    ['Por que a osmose é tão importante para as células e como ela afeta plantas em solo seco?', 'O que acontece com glóbulos vermelhos em soluções hipotônica, isotônica e hipertônica?']),
  createLesson('g1-bio-b1-l6', 'L6: Organelas Celulares — O Núcleo e o Citoplasma', 'biologia',
    'O núcleo guarda o DNA (genoma) e é o centro de controle celular. A carioteca é a dupla membrana que o envolve, com poros nucleares. O nucléolo produz RNA ribossomal. O citoplasma contém o citosol (solução aquosa) e as organelas. O citoesqueleto (actina, tubulina) dá forma e permite o movimento celular.',
    ['Por que o núcleo é chamado de "centro de controle" da célula?', 'Como o citoesqueleto permite que células como os macrófagos se movam em direção às bactérias?']),
  createLesson('g1-bio-b1-l7', 'L7: Retículo Endoplasmático e Complexo de Golgi', 'biologia',
    'Retículo Endoplasmático Rugoso (RER): tem ribossomos, produz e processa proteínas destinadas à secreção ou membranas. Retículo Endoplasmático Liso (REL): sem ribossomos, sintetiza lipídios e desintoxica a célula (especialmente nas células do fígado). Complexo de Golgi: modifica, empacota e distribui proteínas — o "correio" da célula.',
    ['Por que células que produzem muitos hormônios (proteínas) têm RER muito desenvolvido?', 'Como o Complexo de Golgi seleciona e direciona proteínas para seus destinos corretos?']),
  createLesson('g1-bio-b1-l8', 'L8: Mitocôndrias e Cloroplastos — Organelas de Energia', 'biologia',
    'Mitocôndrias ("usinas de energia") produzem ATP pela respiração celular aeróbia. Têm DNA próprio, dupla membrana e ribossomos — evidência de origem como bactérias endossimbiônticas (Teoria da Endossimbiose, Lynn Margulis). Cloroplastos (em células vegetais e algas) realizam fotossíntese, também têm DNA próprio e dupla membrana.',
    ['O que é a Teoria da Endossimbiose e quais evidências a apoiam?', 'Por que mitocôndrias são herdadas exclusivamente pela mãe nos seres humanos?']),
  createLesson('g1-bio-b1-l9', 'L9: Lisossomos, Vacúolos e Peroxissomos', 'biologia',
    'Lisossomos contêm enzimas digestivas ácidas (pH ~5) e degradam material intracelular antigo (autofagia) e partículas engolfadas (fagocitose). Vacúolos vegetais: grandes, armazenam água, pigmentos e metabólitos; mantêm a turgescência. Peroxissomos: degradam ácidos graxos e detoxificam H₂O₂ (água oxigenada) com catalase.',
    ['O que é autofagia e por que ela é essencial para a saúde celular?', 'Por que a falta de enzimas lisossômicas causa doenças de armazenamento, como a Doença de Gaucher?']),
  createLesson('g1-bio-b1-l10', 'L10: Célula Vegetal vs. Célula Animal', 'biologia',
    'Diferenças entre células vegetais e animais: células vegetais têm parede celular (celulose), cloroplastos e vacúolo central grande. Células animais têm centríolos (organizam o fuso mitótico) e, em muitos tipos, lisossomos mais abundantes. Ambas têm membrana, núcleo, mitocôndrias, ribossomos, RE e Golgi.',
    ['Por que as plantas não precisam ingerir alimento como os animais?', 'Como a parede celular de celulose confere rigidez às plantas e por que os animais não têm essa estrutura?']),
  createLesson('g1-bio-b1-l11', 'L11: Bioquímica — Água e Sais Minerais', 'biologia',
    'A água representa 65-75% da massa corporal e tem propriedades únicas: alto calor específico (estabiliza temperatura), alta tensão superficial, excelente solvente (solvente universal polar), participa de reações (hidrólise) e tem densidade menor no estado sólido (gelo flutua). Os sais minerais são cofatores enzimáticos e mantêm o equilíbrio osmótico.',
    ['Por que a água é essencial para a vida em múltiplos níveis?', 'Qual o papel do ferro (Fe²⁺) no transporte de oxigênio pela hemoglobina?']),
  createLesson('g1-bio-b1-l12', 'L12: Bioquímica — Carboidratos', 'biologia',
    'Carboidratos têm fórmula geral (CH₂O)ₙ e são a principal fonte de energia celular. Monossacarídeos: glicose, frutose, galactose (energia imediata). Dissacarídeos: sacarose (cana-de-açúcar — Brasil é o maior produtor), lactose (leite), maltose. Polissacarídeos: amido (reserva vegetal), glicogênio (reserva animal — no fígado e músculo), celulose (estrutural nas plantas).',
    ['Por que o glicogênio hepático é importante para manter a glicemia estável durante o jejum?', 'Como o Brasil se tornou líder mundial na produção de sacarose e etanol?']),
  createLesson('g1-bio-b1-l13', 'L13: Bioquímica — Lipídios', 'biologia',
    'Lipídios são moléculas apolares ricas em C e H. Triglicerídeos (gorduras/óleos): reserva energética e isolamento térmico. Fosfolipídios: formam a bicamada da membrana celular. Esteroides: colesterol (membrana e precursor de hormônios), hormônios sexuais (testosterona, estrogênio), vitamina D. Ceras: impermeabilizam superfícies (cutícula de insetos e plantas).',
    ['Por que o colesterol é necessário para a membrana plasmática mesmo sendo associado a riscos cardiovasculares?', 'Como os lipídios servem como isolante térmico em mamíferos de regiões frias?']),
  createLesson('g1-bio-b1-l14', 'L14: Bioquímica — Proteínas', 'biologia',
    'Proteínas são polímeros de aminoácidos ligados por ligações peptídicas. Os 20 aminoácidos variam no grupo R lateral. Funções: enzimática (catálise), estrutural (colágeno, queratina), transporte (hemoglobina, albumina), hormonal (insulina), defesa (anticorpos), contração (actina e miosina). A estrutura tridimensional determina a função.',
    ['Como a insulina, uma proteína hormonal, regula a glicemia no diabetes tipo 1?', 'Por que a desnaturação de uma proteína (ex: ao cozinhar o ovo) a torna inativa?']),
  createLesson('g1-bio-b1-l15', 'L15: Enzimas — Catalisadores Biológicos', 'biologia',
    'Enzimas são proteínas que catalisam reações biológicas: aumentam a velocidade sem ser consumidas. O substrato se liga ao sítio ativo (modelo chave-fechadura ou encaixe induzido). Fatores que afetam a atividade enzimática: temperatura (cada enzima tem temperatura ótima — pepsina a 37°C, enzimas de bactérias termófilas a >80°C), pH e concentração de substrato.',
    ['Por que tomar antibióticos que inibem enzimas bacterianas pode curar infecções sem prejudicar as células humanas?', 'Como a temperatura afeta a atividade das enzimas digestivas no estômago?']),
  createLesson('g1-bio-b1-l16', 'L16: Bioquímica — Ácidos Nucleicos (DNA e RNA)', 'biologia',
    'DNA (ácido desoxirribonucleico): dupla hélice, bases A-T e G-C, contém a informação genética no núcleo. RNA (ácido ribonucleico): fita simples, base U no lugar de T. Tipos de RNA: mRNA (mensageiro — leva a informação do DNA ao ribossomo), tRNA (transportador — carrega aminoácidos), rRNA (ribossomal — forma o ribossomo). Juntos, realizam a síntese proteica.',
    ['Qual a relação entre DNA, RNA e proteínas (Dogma Central da Biologia Molecular)?', 'Por que o DNA está no núcleo mas as proteínas são sintetizadas no citoplasma?']),
  createLesson('g1-bio-b1-l17', 'L17: Vírus — Estrutura e Doenças', 'biologia',
    'Vírus são acelulares: têm material genético (DNA ou RNA) envolto por proteínas (capsídeo) e, às vezes, envelope lipídico. São parasitas intracelulares obrigatórios: só se reproduzem dentro de células hospedeiras. Doenças virais no Brasil: dengue, zika, chikungunya (Aedes aegypti), COVID-19, gripe, HPV, hepatite B e C, raiva, febre amarela.',
    ['Por que antibióticos não funcionam contra vírus?', 'Como o vírus da dengue infecta células humanas e por que ele causa tanta mortalidade no Brasil?']),
  createLesson('g1-bio-b1-l18', 'L18: Revisão — Citologia e Bioquímica', 'biologia',
    'A célula é a unidade fundamental da vida. Suas organelas trabalham integradas para manter o metabolismo. As biomoléculas (carboidratos, lipídios, proteínas e ácidos nucleicos) executam todas as funções vitais. Compreender a estrutura celular é a base para entender genética, evolução, ecologia e medicina.',
    ['Desenhe uma célula eucariótica e identifique as funções de cada organela.', 'Como a integração entre DNA, proteínas e metabolismo celular sustenta a vida?']),
];

export const bioLessonsB2: Lesson[] = [
  createLesson('g1-bio-b2-l1', 'L1: Metabolismo Celular — Visão Geral', 'biologia',
    'Metabolismo é o conjunto de todas as reações químicas de uma célula. Reações anabólicas (anabolismo) constroem moléculas complexas consumindo energia (ex: síntese proteica, fotossíntese). Reações catabólicas (catabolismo) degradam moléculas complexas liberando energia (ex: respiração celular, digestão). O ATP é a "moeda energética" universal das células.',
    ['Qual a diferença entre anabolismo e catabolismo? Dê um exemplo de cada.', 'Por que o ATP é chamado de "moeda energética" e como ele armazena energia nas células?']),
  createLesson('g1-bio-b2-l2', 'L2: Fotossíntese — Fase Clara', 'biologia',
    'Fotossíntese ocorre nos cloroplastos. A equação geral é: 6CO₂ + 6H₂O + luz → C₆H₁₂O₆ + 6O₂. A fase clara (fotoquímica) ocorre nas membranas tilacoidais: a clorofila absorve luz, divide a água (fotólise — libera O₂), e produz ATP e NADPH. Os fotossistemas I e II atuam em sequência (cadeia de transporte de elétrons nos cloroplastos).',
    ['Por que as folhas são verdes? Que cores da luz a clorofila absorve?', 'De onde vem o oxigênio liberado na fotossíntese: do CO₂ ou da H₂O?']),
  createLesson('g1-bio-b2-l3', 'L3: Fotossíntese — Fase Escura (Ciclo de Calvin)', 'biologia',
    'A fase escura (ciclo de Calvin) ocorre no estroma do cloroplasto e não necessita diretamente de luz. Usa o CO₂ do ar, o ATP e o NADPH da fase clara para sintetizar G3P (gliceraldeído-3-fosfato), precursor da glicose. O RuBisCO é a enzima central do ciclo. As plantas C4 (milho, cana) e CAM (cactos) têm adaptações para fotossíntese em ambientes quentes e secos.',
    ['Por que a fase escura não funciona sem a fase clara, apesar de não precisar de luz diretamente?', 'Por que as plantas C4 como a cana-de-açúcar são mais eficientes em climas quentes que as plantas C3?']),
  createLesson('g1-bio-b2-l4', 'L4: Fatores que Afetam a Fotossíntese', 'biologia',
    'A taxa fotossintética é influenciada por: intensidade luminosa (aumenta até o ponto de saturação), concentração de CO₂ (fator limitante em condições normais — por isso elevação de CO₂ atmosférico pode aumentar produtividade agrícola), temperatura (ótima ~25-30°C para a maioria), disponibilidade de água e minerais (Mg no centro da clorofila, Fe nas proteínas da cadeia de transporte).',
    ['Como o efeito estufa (aumento de CO₂) afeta a taxa de fotossíntese das plantas do Cerrado?', 'Por que folhas à sombra têm mais clorofila que folhas ao sol pleno?']),
  createLesson('g1-bio-b2-l5', 'L5: Respiração Celular Aeróbia — Glicólise', 'biologia',
    'Respiração celular aeróbia ocorre em 3 etapas. Glicólise (citosol): glicose (6C) → 2 piruvatos (3C) + 2 ATP + 2 NADH. É anaeróbia (não precisa de O₂). É a mais antiga via metabólica evolutivamente — presente em todos os seres vivos. Ocorre no citosol.',
    ['Por que a glicólise é considerada a via metabólica mais primitiva da evolução?', 'Quantos ATP são produzidos na glicólise e como eles se comparam ao total da respiração aeróbia?']),
  createLesson('g1-bio-b2-l6', 'L6: Respiração Celular Aeróbia — Ciclo de Krebs', 'biologia',
    'Ciclo de Krebs (Ciclo do Ácido Cítrico — na matriz mitocondrial): o piruvato da glicólise é convertido em acetil-CoA (2C) liberando CO₂ e NADH. O acetil-CoA entra no ciclo, produzindo CO₂, NADH, FADH₂ e 2 ATP por glicose. O CO₂ exalado na respiração vem do Ciclo de Krebs.',
    ['De onde vem o CO₂ que exalamos ao respirar?', 'Por que células que precisam de muita energia (como as do coração) têm mais mitocôndrias?']),
  createLesson('g1-bio-b2-l7', 'L7: Respiração Celular — Cadeia Transportadora de Elétrons e ATP Sintase', 'biologia',
    'A cadeia transportadora (na membrana interna da mitocôndria) usa NADH e FADH₂ para bombear H⁺ para o espaço intermembranar, criando gradiente eletroquímico. O O₂ é o aceptor final de elétrons (forma H₂O). A ATP sintase usa o fluxo de H⁺ de volta para a matriz para produzir ~34 ATP. Total da respiração aeróbia: ~36-38 ATP por glicose.',
    ['Por que o O₂ é essencial para a respiração aeróbia e o que acontece quando falta O₂?', 'Como o veneno cianeto mata ao bloquear a cadeia transportadora de elétrons?']),
  createLesson('g1-bio-b2-l8', 'L8: Respiração Anaeróbia e Fermentação', 'biologia',
    'Na ausência de O₂, as células fazem fermentação para regenerar NAD⁺ e continuar a glicólise. Fermentação alcoólica (leveduras): piruvato → etanol + CO₂ (base da produção de pão, cerveja, vinho e etanol combustível no Brasil). Fermentação lática (músculos e bactérias): piruvato → lactato (causa dor muscular; base de iogurte e queijo).',
    ['Por que sentimos "cansaço muscular" (ardência) durante exercícios intensos?', 'Como o etanol combustível brasileiro é produzido pela fermentação alcoólica da cana-de-açúcar?']),
  createLesson('g1-bio-b2-l9', 'L9: Comparação: Fotossíntese × Respiração Celular', 'biologia',
    'Fotossíntese e respiração aeróbia são processos opostos e complementares. Fotossíntese: consome CO₂ e H₂O, produz glicose e O₂, armazena energia solar em energia química. Respiração: consome glicose e O₂, produz CO₂ e H₂O, libera energia do ATP. O balanço desses dois processos regula a concentração de CO₂ e O₂ na atmosfera.',
    ['Qual o papel das florestas brasileiras (Amazônia e Cerrado) no equilíbrio entre fotossíntese e respiração global?', 'Por que plantas também respiram além de fotossintetizar?']),
  createLesson('g1-bio-b2-l10', 'L10: Divisão Celular — Ciclo Celular', 'biologia',
    'O ciclo celular compreende: Interfase (G1 — crescimento; S — replicação do DNA; G2 — preparação para divisão) e Fase M (mitose ou meiose). Os checkpoints (pontos de verificação) garantem que a divisão só ocorra se o DNA foi corretamente replicado e sem danos. Falhas nos checkpoints podem levar ao desenvolvimento de câncer.',
    ['Por que é essencial que o DNA seja completamente replicado antes da divisão celular?', 'Como as falhas nos checkpoints do ciclo celular contribuem para o desenvolvimento de câncer?']),
  createLesson('g1-bio-b2-l11', 'L11: Mitose — Fases e Importância', 'biologia',
    'Mitose é a divisão celular que gera duas células-filhas geneticamente idênticas à célula-mãe (mesmo número de cromossomos). Fases: Prófase (cromossomos condensam, fuso se forma), Metáfase (cromossomos no equador), Anáfase (cromátides se separam), Telófase (núcleos se reconstituem) e Citocinese (divisão do citoplasma). Importância: crescimento, regeneração e reprodução assexuada.',
    ['Por que a mitose deve produzir células-filhas com o mesmo número de cromossomos da célula-mãe?', 'Como nosso fígado se regenera após uma cirurgia parcial usando a mitose?']),
  createLesson('g1-bio-b2-l12', 'L12: Meiose — Fases e Importância', 'biologia',
    'Meiose produz 4 células-filhas haploides (n) a partir de uma célula diploide (2n), com material genético diversificado. Ocorre em duas divisões: Meiose I (divisão reducional — separa homólogos) e Meiose II (divisão equacional — separa cromátides). Durante a meiose I ocorre o crossing-over (recombinação genética), gerando diversidade. Produz gametas (óvulos e espermatozoides) e esporos.',
    ['Por que a meiose é essencial para a reprodução sexual e a biodiversidade?', 'O que é crossing-over e como ele aumenta a variabilidade genética da espécie?']),
  createLesson('g1-bio-b2-l13', 'L13: Comparação: Mitose × Meiose', 'biologia',
    'Mitose: 2 células-filhas 2n idênticas, para crescimento e regeneração. Meiose: 4 células-filhas n variadas, para formação de gametas/esporos. Ambas têm fases similares (pro, meta, ana, telófase), mas a meiose tem duas divisões e inclui o crossing-over. Erros na meiose causam aneuploidias como a Síndrome de Down (trissomia do cromossomo 21).',
    ['Por que a Síndrome de Down ocorre com maior frequência em filhos de mães mais velhas?', 'Quais são as principais diferenças entre mitose e meiose em uma tabela comparativa?']),
  createLesson('g1-bio-b2-l14', 'L14: Câncer — Divisão Celular Descontrolada', 'biologia',
    'Câncer resulta de mutações em genes que controlam o ciclo celular: proto-oncogenes (estimulam divisão) tornam-se oncogenes quando mutados; genes supressores tumorais (como p53) freiam a divisão e, quando inativados, permitem crescimento descontrolado. Fatores de risco: tabaco (maior causa evitável), radiação UV, vírus (HPV → câncer de colo do útero), agentes químicos.',
    ['Como o tabagismo causa mutações que levam ao câncer de pulmão?', 'Como a vacinação contra HPV previne o câncer de colo do útero?']),
  createLesson('g1-bio-b2-l15', 'L15: Histologia — Tecido Epitelial', 'biologia',
    'Os tecidos são grupos de células com estrutura e função semelhantes. Tecido epitelial: cobre superfícies e reveste cavidades. Classificação: por número de camadas (simples, estratificado, pseudoestratificado) e forma das células (pavimentoso, cúbico, cilíndrico). Funções: proteção (pele), absorção (intestino), secreção (glândulas), sensorial. Não tem vasos sanguíneos (avascular).',
    ['Por que o epitélio do intestino delgado tem microvilosidades?', 'Como a pele (tecido epitelial estratificado) protege o organismo contra patógenos?']),
  createLesson('g1-bio-b2-l16', 'L16: Histologia — Tecido Conjuntivo', 'biologia',
    'Tecido conjuntivo tem abundante matriz extracelular (proteínas + polissacarídeos). Tipos: conjuntivo propriamente dito (frouxo e denso — tendões, ligamentos), cartilagem (hialina — articulações, elástica — orelha, fibrosa — menisco), osso (suporte e minerais), sangue (transporte) e tecido adiposo (reserva energética e isolamento térmico).',
    ['Por que lesões em cartilagem (como menisco) demoram tanto para cicatrizar?', 'Qual a diferença entre tendão e ligamento em termos de tecido conjuntivo e função?']),
  createLesson('g1-bio-b2-l17', 'L17: Histologia — Tecidos Muscular e Nervoso', 'biologia',
    'Tecido muscular: estriado esquelético (contração voluntária, rápida — movimento), estriado cardíaco (involuntário, ritmado — coração) e liso (involuntário, lento — vísceras, vasos). Tecido nervoso: neurônios (conduzem impulsos elétricos: axônio, dendrito, corpo celular) e células gliais (suporte, mielinização, nutrição). Sistema nervoso = tecido nervoso organizado.',
    ['Por que o músculo cardíaco não para mesmo durante o sono?', 'Como a mielina acelera a condução do impulso nervoso e o que acontece na esclerose múltipla?']),
  createLesson('g1-bio-b2-l18', 'L18: Revisão — Metabolismo Celular e Histologia', 'biologia',
    'Fotossíntese e respiração são os processos centrais do metabolismo. Mitose e meiose garantem reprodução e herança genética. Os quatro tecidos básicos (epitelial, conjuntivo, muscular e nervoso) formam todos os órgãos do corpo humano. Esses conhecimentos são a base para entender anatomia, fisiologia, genética e patologias.',
    ['Como a compreensão do metabolismo celular ajuda no desenvolvimento de novos medicamentos contra o câncer?', 'Quais tecidos básicos compõem o coração e qual é a função de cada um?']),
];

export const bioLessonsB3: Lesson[] = [
  createLesson('g1-bio-b3-l1', 'L1: Genética — Introdução e Mendel', 'biologia',
    'Gregor Mendel (1865) estudou ervilhas e formulou as leis da herança genética. Descobriu que características são herdadas em unidades discretas (hoje chamadas genes). A 1ª Lei (Segregação): cada indivíduo possui dois alelos para cada gene; na formação dos gametas, os alelos se separam. Dominância: o fenótipo dominante se expressa tanto em homozigotos (AA) quanto heterozigotos (Aa).',
    ['Por que o trabalho de Mendel ficou esquecido por 35 anos antes de ser redescoberto?', 'Qual a diferença entre genótipo (AA, Aa, aa) e fenótipo (cor, forma, altura)?']),
  createLesson('g1-bio-b3-l2', 'L2: 1ª Lei de Mendel — Monoibridismo', 'biologia',
    'Cruzamento monoíbrido: envolve um único par de alelos contrastantes. Em um cruzamento Aa × Aa, a proporção genotípica é 1 AA : 2 Aa : 1 aa (25:50:25%) e a fenotípica é 3 dominante : 1 recessivo (75:25%). O Quadrado de Punnett é ferramenta visual para calcular essas proporções. Teste da progênie (cruzamento-teste com aa) revela o genótipo do dominante.',
    ['Em um cruzamento Aa × Aa, qual a probabilidade de um filho ter o fenótipo recessivo?', 'Como o cruzamento-teste revela se um indivíduo de fenótipo dominante é AA ou Aa?']),
  createLesson('g1-bio-b3-l3', 'L3: 2ª Lei de Mendel — Diibridismo', 'biologia',
    '2ª Lei (Segregação Independente): genes para características diferentes, em cromossomos diferentes, segregam independentemente na formação dos gametas. Cruzamento AaBb × AaBb gera proporção 9:3:3:1 (9 A_B_ : 3 A_bb : 3 aaB_ : 1 aabb). Esta lei vale para genes em cromossomos diferentes (não ligados).',
    ['Por que a 2ª Lei de Mendel não se aplica a genes localizados no mesmo cromossomo?', 'Em um cruzamento AaBb × AaBb, qual a probabilidade de obter um descendente com os dois traços recessivos?']),
  createLesson('g1-bio-b3-l4', 'L4: Dominância Incompleta e Codominância', 'biologia',
    'Dominância incompleta: o heterozigoto (Aa) tem fenótipo intermediário entre os dois homozigotos. Ex: flores vermelhas (AA) × brancas (aa) → flores rosas (Aa). A proporção fenotípica é 1:2:1. Codominância: ambos os alelos se expressam simultaneamente no heterozigoto. Ex: grupo sanguíneo AB (Iᴬ Iᴮ — ambos os antígenos A e B aparecem). São desvios do padrão mendeliano.',
    ['Por que a codominância é diferente da dominância incompleta?', 'Como o sistema ABO de grupos sanguíneos demonstra codominância e recessividade no mesmo locus?']),
  createLesson('g1-bio-b3-l5', 'L5: Herança dos Grupos Sanguíneos (ABO e Rh)', 'biologia',
    'Sistema ABO: controlado por gene I com três alelos: Iᴬ (dominante sobre i, codominante com Iᴮ), Iᴮ e i (recessivo). Grupo A: IᴬIᴬ ou Iᴬi. Grupo B: IᴮIᴮ ou Iᴮi. Grupo AB: IᴬIᴮ. Grupo O: ii. Sistema Rh: gene D. Rh+ (DD ou Dd) dominante. Rh- (dd). Eritroblastose fetal ocorre quando mãe Rh- tem filho Rh+. No Brasil, grupo O+ é o mais comum.',
    ['Quais os possíveis genótipos de um indivíduo do grupo A?', 'O que é eritroblastose fetal e como a imunoglobulina anti-Rh previne essa complicação?']),
  createLesson('g1-bio-b3-l6', 'L6: Herança Ligada ao Sexo', 'biologia',
    'Genes localizados nos cromossomos sexuais (X e Y). Mulheres: XX. Homens: XY. Genes do cromossomo X são chamados ligados ao X. Como homens têm apenas um X, um alelo recessivo ligado ao X já se expressa (hemizigoto). Exemplos: daltonismo (cegueira para cores) e hemofilia A (deficiência no fator VIII de coagulação). Mais frequentes em homens.',
    ['Por que o daltonismo e a hemofilia são muito mais comuns em homens do que em mulheres?', 'Uma mulher portadora de hemofilia (Xᴴ Xʰ) tem filhos com um homem normal. Qual a probabilidade de um filho hemofílico?']),
  createLesson('g1-bio-b3-l7', 'L7: Heredograma — Análise de Heredogramas', 'biologia',
    'Heredograma é a representação gráfica da transmissão de uma característica numa família. Símbolos: quadrado (homem), círculo (mulher), preenchido (afetado). Para determinar o padrão de herança: verificar se é autossômico ou ligado ao X, dominante ou recessivo, e determinar os genótipos dos indivíduos. Heredogramas são usados em aconselhamento genético.',
    ['Como você determina se uma doença num heredograma é autossômica ou ligada ao X?', 'Quais informações são necessárias para calcular o risco de recorrência de uma doença genética em um casal?']),
  createLesson('g1-bio-b3-l8', 'L8: Alelos Múltiplos e Poligenia', 'biologia',
    'Alelos múltiplos: mais de dois alelos possíveis para o mesmo locus (mas cada indivíduo tem apenas dois). Ex: sistema ABO (3 alelos: Iᴬ, Iᴮ, i). Poligenia (herança quantitativa): uma característica é controlada por múltiplos genes. Ex: cor de pele, altura, peso, inteligência. O ambiente influencia muito os traços poligênicos. A distribuição forma uma curva normal.',
    ['Por que a cor de pele humana tem tantas tonalidades intermediárias (herança poligênica)?', 'Como os fatores ambientais (nutrição, exercício) interagem com os genes que controlam a altura?']),
  createLesson('g1-bio-b3-l9', 'L9: Mutações Gênicas e Cromossômicas', 'biologia',
    'Mutação gênica: alteração na sequência de bases do DNA. Pode ser pontual (substituição de uma base — ex: anemia falciforme, onde um único nucleotídeo muda o aminoácido da hemoglobina) ou por inserção/deleção (frameshift). Mutação cromossômica: alteração no número (aneuploidia — Síndrome de Down: +1 cromossomo 21) ou estrutura dos cromossomos (deleção, inversão, translocação).',
    ['Como uma única mutação pontual no gene da hemoglobina causa anemia falciforme e por que essa mutação é mais comum em populações afrodescendentes?', 'Qual a diferença entre mutação gênica e mutação cromossômica?']),
  createLesson('g1-bio-b3-l10', 'L10: Síndromes Genéticas', 'biologia',
    'Síndrome de Down (trissomia 21): 47 cromossomos, características físicas específicas, comprometimento cognitivo variável. Síndrome de Turner (XO): mulher com um X, baixa estatura e infertilidade. Síndrome de Klinefelter (XXY): homem com cromossomo X extra, infertilidade. Síndrome de Patau (trissomia 13) e Edwards (trissomia 18) são mais graves. Diagnóstico pré-natal: amniocentese e biópsia de vilo corial.',
    ['Como o aumento da idade materna aumenta o risco de trissomias como a Síndrome de Down?', 'Quais as opções de diagnóstico pré-natal para detectar síndromes cromossômicas e quando elas são indicadas?']),
  createLesson('g1-bio-b3-l11', 'L11: DNA — Estrutura e Replicação', 'biologia',
    'DNA tem estrutura de dupla hélice antiparalela: fitas de fosfato-açúcar com bases nitrogenadas pareadas (A-T por 2 pontes de H; G-C por 3 pontes de H). A replicação é semiconservativa: cada fita serve de molde para uma nova fita. Enzimas: DNA polimerase (sintetiza a nova fita), helicase (abre a hélice), ligase (une fragmentos). Ocorre durante a fase S da interfase.',
    ['Por que a replicação do DNA é chamada de "semiconservativa"?', 'Como os erros durante a replicação do DNA são corrigidos e o que acontece quando não são?']),
  createLesson('g1-bio-b3-l12', 'L12: Transcrição — DNA para RNA', 'biologia',
    'Na transcrição, um segmento de DNA serve de molde para sintetizar uma molécula de mRNA complementar. A RNA polimerase lê o DNA no sentido 3\'→5\' e sintetiza o mRNA no sentido 5\'→3\'. Células eucarióticas: o pré-mRNA sofre processamento (splicing — remoção dos íntrons, união dos éxons; adição de cap 5\' e cauda poli-A) antes de sair do núcleo.',
    ['O que é splicing alternativo e como um único gene pode codificar múltiplas proteínas diferentes?', 'Qual é a função do promotor e como os fatores de transcrição regulam a expressão gênica?']),
  createLesson('g1-bio-b3-l13', 'L13: Tradução — RNA para Proteína', 'biologia',
    'Na tradução, o ribossomo lê o mRNA em códons (tripletos de bases) e sintetiza a proteína correspondente. O código genético é universal, não sobreponível e degenerado (vários códons para um aminoácido). O tRNA carrega o aminoácido ao ribossomo, pareando seu anticódon com o códon do mRNA. Os códons de início (AUG — metionina) e parada (UAA, UAG, UGA) delimitam a proteína.',
    ['Por que o código genético ser universal é uma evidência forte da evolução comum de todos os seres vivos?', 'O que é um códon de parada e o que acontece quando uma mutação cria um códon de parada prematuro?']),
  createLesson('g1-bio-b3-l14', 'L14: Biotecnologia — DNA Recombinante', 'biologia',
    'Engenharia genética usa enzimas de restrição para cortar o DNA em pontos específicos, criando "pontas coesivas". O fragmento de DNA pode ser inserido em um vetor (plasmídeo ou vírus) e introduzido em uma célula hospedeira (bactéria, levedura). Aplicações: produção de insulina humana por bactérias, hormônio do crescimento, vacinas recombinantes (hepatite B) e diagnósticos moleculares (PCR).',
    ['Como a insulina humana é produzida por bactérias geneticamente modificadas?', 'Quais são os benefícios e os riscos éticos do uso de organismos geneticamente modificados?']),
  createLesson('g1-bio-b3-l15', 'L15: Transgênicos e Organismos Geneticamente Modificados (OGMs)', 'biologia',
    'OGMs têm genes de outras espécies inseridos em seu genoma. Brasil é o 2º maior produtor de OGMs (soja Bt, milho Bt — resistentes a insetos; soja RR — resistente ao herbicida glifosato). A CTNBio aprova e regula OGMs no Brasil. Benefícios: maior produtividade, menos pesticidas. Riscos: impacto em biodiversidade, dependência tecnológica de multinacionais.',
    ['Quais os argumentos a favor e contra os OGMs na agricultura brasileira?', 'Como a soja Bt produz sua própria proteína inseticida e por que isso pode reduzir o uso de agrotóxicos?']),
  createLesson('g1-bio-b3-l16', 'L16: PCR e Sequenciamento Genético', 'biologia',
    'PCR (Reação em Cadeia da Polimerase): amplifica milhões de cópias de um segmento específico de DNA a partir de quantidades mínimas. Usos: diagnóstico de doenças (COVID-19, dengue, HIV), medicina forense (DNA de cenas de crime), paleontologia (DNA antigo). Sequenciamento de Sanger e de nova geração (NGS) permitem ler a sequência do DNA — base da medicina de precisão.',
    ['Como o teste PCR para COVID-19 funciona e por que é mais sensível que os testes rápidos de antígeno?', 'Como a medicina de precisão usa o sequenciamento genético para personalizar tratamentos de câncer?']),
  createLesson('g1-bio-b3-l17', 'L17: Genômica e Projeto Genoma Humano', 'biologia',
    'O Projeto Genoma Humano (1990-2003) sequenciou os ~3,2 bilhões de pares de bases do DNA humano e identificou ~20.000-25.000 genes. Revelou que apenas ~1,5% do DNA codifica proteínas (o restante era chamado de "DNA lixo" — agora sabe-se que tem funções regulatórias). O Brasil participou sequenciando o Xylella fastidiosa (fitopatógeno da laranja).',
    ['O que o Projeto Genoma Humano revelou que surpreendeu os cientistas sobre a quantidade de genes?', 'Quais aplicações médicas surgiram do conhecimento do genoma humano completo?']),
  createLesson('g1-bio-b3-l18', 'L18: Revisão — Genética e Biologia Molecular', 'biologia',
    'Genética e biologia molecular são pilares da biologia moderna. As leis de Mendel explicam a herança. O DNA guarda a informação genética, transcrita para RNA e traduzida em proteínas. Mutações geram variabilidade e doenças. A engenharia genética transforma a medicina e a agricultura. O ENEM valoriza muito a aplicação social e ética desses conhecimentos.',
    ['Como as Leis de Mendel e o Dogma Central da Biologia Molecular se conectam?', 'Quais são os principais desafios éticos da manipulação genética nos seres vivos?']),
];

export const bioLessonsB4: Lesson[] = [
  createLesson('g1-bio-b4-l1', 'L1: Evolução — Lamarckismo', 'biologia',
    'Jean-Baptiste Lamarck (1809) propôs a primeira teoria evolutiva sistemática. Princípios: Lei do Uso e Desuso (órgãos muito usados se desenvolvem; pouco usados atrofiam) e Lei da Herança dos Caracteres Adquiridos (características adquiridas durante a vida são transmitidas aos filhos). Embora refutada, foi um passo crucial ao propor que as espécies mudam ao longo do tempo.',
    ['Por que a teoria de Lamarck foi refutada pela ciência moderna?', 'O que Lamarck e Darwin têm em comum e em que diferem sobre o mecanismo da evolução?']),
  createLesson('g1-bio-b4-l2', 'L2: Evolução — Darwinismo', 'biologia',
    'Charles Darwin (A Origem das Espécies, 1859) propôs a teoria da Evolução por Seleção Natural: há variabilidade natural nas populações; organismos se reproduzem em excesso; há competição por recursos; os mais adaptados sobrevivem e se reproduzem mais; as características adaptativas são herdadas. Alfred Russel Wallace chegou às mesmas conclusões independentemente.',
    ['O que Darwin observou nas ilhas Galápagos que o inspirou a formular a teoria da seleção natural?', 'Por que a seleção natural favorece adaptações ao ambiente atual, não ao futuro?']),
  createLesson('g1-bio-b4-l3', 'L3: Neodarwinismo — A Síntese Moderna', 'biologia',
    'O Neodarwinismo (Síntese Moderna, séc. XX) integra Darwin com a genética de Mendel e a genética de populações. As mutações e recombinações genéticas geram variabilidade. A seleção natural atua sobre essa variabilidade. Outros mecanismos evolutivos: deriva genética (aleatória, mais intensa em populações pequenas), fluxo gênico (migração), especiação.',
    ['O que os neodarwinistas adicionaram à teoria de Darwin para completar a compreensão da evolução?', 'Por que a deriva genética é mais intensa em populações pequenas, como comunidades isoladas?']),
  createLesson('g1-bio-b4-l4', 'L4: Evidências da Evolução', 'biologia',
    'Múltiplas linhas de evidência apoiam a evolução: paleontologia (fósseis mostram formas ancestrais — fósseis do Triângulo Mineiro e do Araripe no Brasil), anatomia comparada (homologias: asa de morcego, braço humano, nadadeira de baleia têm messos ossos; análogos: asa de morcego e de inseto têm função similar mas origem diferente), embriologia comparada, biogeografia e evidências moleculares (DNA).',
    ['Por que estruturas homólogas são uma evidência forte de ancestralidade comum?', 'Como a análise molecular do DNA de diferentes espécies confirma as árvores filogenéticas?']),
  createLesson('g1-bio-b4-l5', 'L5: Seleção Natural — Tipos e Exemplos', 'biologia',
    'Tipos de seleção natural: estabilizadora (favorece o fenótipo intermediário — ex: peso ao nascer em humanos), direcional (favorece um extremo — ex: resistência a antibióticos em bactérias) e disruptiva (favorece os dois extremos — pode levar à especiação). O melanism industrial das mariposas Biston betularia demonstrou seleção direcional em tempo real.',
    ['Como a seleção direcional explica o rápido desenvolvimento de resistência de bactérias a antibióticos?', 'Por que o uso inadequado de antibióticos é um grave problema de saúde pública no Brasil?']),
  createLesson('g1-bio-b4-l6', 'L6: Especiação', 'biologia',
    'Especiação é o processo pelo qual uma espécie ancestral dá origem a duas ou mais novas espécies. Especiação alopátrica: populações separadas geograficamente evoluem independentemente até a incompatibilidade reprodutiva (rio Tocantins isola populações de peixes e aves). Especiação simpátrica: ocorre sem isolamento geográfico, por poliploidia (comum em plantas) ou nicho diferente.',
    ['Como o isolamento geográfico promovido por rios e montanhas contribuiu para a biodiversidade do Cerrado e da Amazônia?', 'O que define uma espécie biológica segundo Ernst Mayr?']),
  createLesson('g1-bio-b4-l7', 'L7: Evolução Humana', 'biologia',
    'Humanos e chimpanzés compartilham ~98,7% do DNA. Nossa linhagem (hominídeos) divergiu há ~6-7 milhões de anos. Australopithecus (África, ~4 ma), Homo habilis (primeiras ferramentas), Homo erectus (migrou para fora da África), Homo sapiens (surgiu na África há ~300 mil anos). Fósseis de Luzia (Lagoa Santa, MG) mostram que a América foi colonizada muito antes do que se pensava.',
    ['Por que compartilhar 98,7% do DNA com chimpanzés não significa que somos 98,7% chimpanzés?', 'O que o estudo do DNA mitocondrial de povos de todo o mundo revelou sobre a origem e migração do Homo sapiens?']),
  createLesson('g1-bio-b4-l8', 'L8: Ecologia — Conceitos Fundamentais', 'biologia',
    'Ecologia estuda as relações entre os seres vivos e seu ambiente. Níveis de organização: indivíduo, população (mesma espécie, mesmo local, mesmo tempo), comunidade (várias populações), ecossistema (comunidade + ambiente abiótico) e biosfera. Habitat é o local onde a espécie vive; nicho ecológico é seu papel funcional nesse habitat.',
    ['Qual a diferença entre habitat e nicho ecológico?', 'Por que a Floresta Amazônica é considerada um ecossistema e não apenas uma floresta?']),
  createLesson('g1-bio-b4-l9', 'L9: Cadeias e Teias Alimentares', 'biologia',
    'Cadeia alimentar: sequência linear de quem come quem. Produtor (planta) → Consumidor primário (herbívoro) → Consumidor secundário (carnívoro 1) → Consumidor terciário. Teia alimentar: rede complexa de cadeias interligadas — mais realista. A energia flui em uma única direção; os nutrientes são reciclados. Decompositores (fungos e bactérias) liberam nutrientes de volta ao solo.',
    ['O que acontece com um ecossistema quando o predador topo (onça-pintada) é removido?', 'Por que a extinção de decompositores seria catastrófica para todos os ecossistemas?']),
  createLesson('g1-bio-b4-l10', 'L10: Pirâmides Ecológicas', 'biologia',
    'Pirâmides ecológicas representam a distribuição de energia, biomassa ou número ao longo dos níveis tróficos. Pirâmide de energia: sempre triangular (energia diminui ~10% a cada nível — Regra dos 10%). Pirâmide de biomassa: pode ser invertida (zooplâncton > fitoplâncton em oceanos). Pirâmide de números: pode ser invertida (parasitas > hospedeiros). A eficiência ecológica explica por que há menos carnívoros que herbívoros.',
    ['Por que a base da cadeia alimentar (produtores) tem sempre muito mais energia que o topo (carnívoros)?', 'Como a pirâmide de energia explica por que comer carne bovina é menos eficiente do que comer vegetais para o planeta?']),
  createLesson('g1-bio-b4-l11', 'L11: Ciclos Biogeoquímicos — Carbono e Nitrogênio', 'biologia',
    'Ciclo do carbono: CO₂ do ar → fotossíntese → matéria orgânica → respiração/decomposição → CO₂. A queima de combustíveis fósseis libera C que estava armazenado por milhões de anos, aumentando o CO₂ atmosférico. Ciclo do nitrogênio: N₂ do ar → fixação (bactérias como Rhizobium em raízes de soja e leguminosas) → nitratos → absorção pelas plantas → proteínas → decomposição → N₂.',
    ['Por que o desmatamento na Amazônia e no Cerrado interfere no ciclo do carbono?', 'Como as bactérias fixadoras de nitrogênio (Rhizobium) reduziram a necessidade de fertilizantes na soja brasileira?']),
  createLesson('g1-bio-b4-l12', 'L12: Relações Ecológicas', 'biologia',
    'Relações harmônicas (beneficiam ao menos um): mutualismo (ambos se beneficiam — abelhas e flores), comensalismo (um se beneficia, outro é neutro — rêmora e tubarão), protocooperação (não obrigatória). Relações desarmônicas (prejudicam ao menos um): predação (predador × presa), parasitismo (parasita prejudica hospedeiro), amensalismo (um prejudica, outro é neutro — penicilina × bactérias) e competição (por recursos).',
    ['Por que o mutualismo entre abelhas e flores é essencial para o agronegócio brasileiro?', 'Como o parasitismo do barbeiro (Triatoma) causa a Doença de Chagas e qual seu impacto na saúde pública do Brasil?']),
  createLesson('g1-bio-b4-l13', 'L13: Biomas Brasileiros', 'biologia',
    'Brasil tem 6 biomas: Amazônia (maior floresta tropical do mundo — maior biodiversidade do planeta), Cerrado (savana brasileira — 2º maior bioma, berço das águas, segunda maior biodiversidade), Mata Atlântica (altamente ameaçada — restam <12%), Caatinga (semiárido — única caatinga do mundo, endêmica), Pantanal (maior planície alagável do mundo) e Pampa (campos sulinos).',
    ['Por que o Cerrado, bioma do Tocantins, é considerado um "hotspot" de biodiversidade em perigo?', 'Qual a relação entre o desmatamento do Cerrado e a redução das nascentes que abastecem bacias hidrográficas como o rio Tocantins?']),
  createLesson('g1-bio-b4-l14', 'L14: Sucessão Ecológica', 'biologia',
    'Sucessão ecológica é a mudança gradual e direcional em uma comunidade ao longo do tempo. Sucessão primária: começa em substrato sem vida (rocha nua — liquens pioneiros). Sucessão secundária: após perturbação (queimada, desmatamento), em solo que já tinha vida — mais rápida. A comunidade clímax é o estágio final relativamente estável. O Cerrado após queimadas naturais exemplifica sucessão secundária rápida.',
    ['Qual a diferença entre sucessão primária e secundária e por que a secundária é mais rápida?', 'Como a recuperação de áreas degradadas no Cerrado usa os princípios da sucessão ecológica?']),
  createLesson('g1-bio-b4-l15', 'L15: Dinâmica de Populações', 'biologia',
    'O crescimento populacional depende de: taxa de natalidade, mortalidade, imigração e emigração. Crescimento exponencial (J): sem limitações. Crescimento logístico (S): limitado pela capacidade de suporte (K) do ambiente. Fatores reguladores: bióticos (predação, doenças, competição) e abióticos (temperatura, seca). A população humana cresceu exponencialmente após a Revolução Industrial.',
    ['Por que a população de lobos num parque nacional segue uma curva logística e não exponencial?', 'Como o crescimento exponencial da população humana até o séc. XX está relacionado com a crise ambiental atual?']),
  createLesson('g1-bio-b4-l16', 'L16: Impactos Ambientais e Conservação', 'biologia',
    'Principais ameaças à biodiversidade: desmatamento (Amazônia e Cerrado — o Tocantins é um dos estados com mais desmatamento do Cerrado), queimadas, caça/pesca predatória, espécies invasoras, poluição e mudanças climáticas. Soluções: unidades de conservação (parques, reservas), corredores ecológicos, reflorestamento, REDD+, fiscalização e educação ambiental.',
    ['Como as Unidades de Conservação (UCs) ajudam a preservar a biodiversidade do Cerrado tocantinense?', 'O que são corredores ecológicos e por que eles são essenciais para evitar a extinção de espécies em habitats fragmentados?']),
  createLesson('g1-bio-b4-l17', 'L17: Biotecnologia e Biodiversidade no Brasil', 'biologia',
    'O Brasil é megadiverso: ~20% de todas as espécies do planeta. A biodiversidade tem valor econômico: fitoterápicos da flora brasileira (planta medicinal do Cerrado — Stryphnodendron adstringens; pau-d\'arco etc.), cosméticos (açaí, buriti), agropecuária (bancos de germoplasma da Embrapa). A biopirataria é crime no Brasil — lei de Biodiversidade (2015) regulariza o acesso.',
    ['Por que a biopirataria é um crime grave que prejudica o Brasil e as comunidades tradicionais?', 'Como as comunidades indígenas e quilombolas são guardiãs do conhecimento sobre a biodiversidade do Cerrado?']),
  createLesson('g1-bio-b4-l18', 'L18: Revisão Final — Evolução e Ecologia', 'biologia',
    'Evolução (Lamarck, Darwin, Neodarwinismo) explica a diversidade da vida e a adaptação das espécies. Ecologia conecta os seres vivos entre si e com o ambiente. Os biomas brasileiros são patrimônios da humanidade e do Tocantins. A conservação da biodiversidade é um desafio científico, econômico, social e ético do século XXI.',
    ['Como a teoria da evolução e a ecologia juntas explicam a distribuição da biodiversidade nos biomas brasileiros?', 'Qual é o papel do cidadão comum na conservação da biodiversidade do Cerrado?']),
];
