
import { Lesson } from './types';
import { createLesson } from './data_helpers';

// Química 3ª Série: 18 aulas por bimestre (Total 72)
export const quiLessonsB1: Lesson[] = [
  createLesson('g3-qui-b1-l1', 'L1: Funções Orgânicas — Introdução', 'quimica',
    'Funções orgânicas são grupos de compostos com estrutura e propriedades semelhantes, determinadas pelo grupo funcional. Os principais grupos funcionais são: hidroxila (-OH), carbonila (C=O), carboxila (-COOH), amino (-NH₂) e halogênios. A identificação do grupo funcional permite prever a reatividade e os usos de um composto.',
    ['O que é um grupo funcional e por que ele determina as propriedades de um composto orgânico?', 'Como você identificaria um ácido carboxílico de um álcool apenas pelo grupo funcional?']),
  createLesson('g3-qui-b1-l2', 'L2: Álcoois — Estrutura e Propriedades', 'quimica',
    'Álcoois têm o grupo hidroxila (-OH) ligado a carbono saturado. Classificam-se em primário, secundário e terciário conforme o carbono ligado ao OH. O etanol (C₂H₅OH) é o mais importante no Brasil: produzido por fermentação da cana-de-açúcar, é combustível, antisséptico e componente de bebidas. O glicerol (triol) é base de sabões e cosméticos.',
    ['Por que o etanol é solúvel em água enquanto álcoois de cadeia longa (como cetanol) não são?', 'Qual o papel do etanol na matriz energética brasileira e quais suas vantagens ambientais?']),
  createLesson('g3-qui-b1-l3', 'L3: Fenóis e Éteres', 'quimica',
    'Fenóis têm o grupo -OH ligado diretamente ao anel benzênico, tornando-os mais ácidos que os álcoois. O fenol é usado como desinfetante e na produção de plásticos (baquelite). Éteres têm dois radicais carbônicos ligados ao oxigênio (R-O-R\'). O éter etílico (dietiléter) foi usado como anestésico; o éter de petróleo é solvente.',
    ['Por que os fenóis são mais ácidos que os álcoois, apesar de ambos terem o grupo -OH?', 'Quais os riscos do uso do éter como anestésico que levaram à sua substituição?']),
  createLesson('g3-qui-b1-l4', 'L4: Aldeídos e Cetonas', 'quimica',
    'Aldeídos têm o grupo carbonila no extremo da cadeia (R-CHO). A formaldeído (HCHO) é conservante e germicida (formol). Cetonas têm a carbonila no interior da cadeia (R-CO-R\'). A acetona (propanona) é solvente amplo. Ambos têm odores característicos: vanilina (aldeído) é o aroma da baunilha; a menta contém mentona (cetona).',
    ['Qual a diferença estrutural entre um aldeído e uma cetona?', 'Como a vanilina e outros aldeídos aromáticos são utilizados na indústria alimentícia brasileira?']),
  createLesson('g3-qui-b1-l5', 'L5: Ácidos Carboxílicos', 'quimica',
    'Ácidos carboxílicos têm o grupo -COOH. São ácidos fracos com odor característico. O ácido acético (CH₃COOH) é o componente ativo do vinagre. O ácido cítrico está em frutas cítricas. O ácido lático causa a dor muscular pós-exercício. Ácidos graxos são ácidos carboxílicos de cadeias longas, componentes dos lipídios.',
    ['Por que o ácido acético do vinagre tem pH maior que o HCl com a mesma molaridade?', 'Qual o papel dos ácidos graxos ômega-3 e ômega-6 na saúde humana?']),
  createLesson('g3-qui-b1-l6', 'L6: Ésteres — Formação e Aplicações', 'quimica',
    'Ésteres formam-se pela reação de esterificação entre ácido carboxílico e álcool: R-COOH + R\'OH ⇌ R-COO-R\' + H₂O. São responsáveis pelos aromas de frutas (acetato de isoamila = banana). As gorduras e óleos são ésteres de glicerol com ácidos graxos (triglicerídeos). Sabões resultam da hidrólise alcalina (saponificação) de gorduras.',
    ['Como é produzido o sabão a partir da saponificação de gorduras animais e vegetais?', 'Por que os ésteres têm aromas agradáveis e são usados em perfumes e aromatizantes artificiais?']),
  createLesson('g3-qui-b1-l7', 'L7: Aminas e Amidas', 'quimica',
    'Aminas derivam da amônia (NH₃) com substituição de H por radicais orgânicos. São bases orgânicas com odor característico. A anilina (amina aromática) é base de corantes. Amidas têm o grupo -CO-NH-. O paracetamol é uma amida. As proteínas são poliamidas naturais (ligações peptídicas = amidas entre aminoácidos).',
    ['Por que as aminas são bases e têm odor de peixe?', 'Como a ligação peptídica (amida) une aminoácidos para formar proteínas?']),
  createLesson('g3-qui-b1-l8', 'L8: Halogenetos Orgânicos', 'quimica',
    'Halogenetos orgânicos têm halogênios (F, Cl, Br, I) ligados ao carbono. O clorofórmio (CHCl₃) foi anestésico. O DDT (organoclorado) foi inseticida proibido por ser persistente no ambiente e bioacumulável. Os CFCs (clorofluorocarbonos) destruíram a camada de ozônio até serem banidos pelo Protocolo de Montreal.',
    ['Por que o DDT, apesar de eficaz contra mosquitos, foi proibido em todo o mundo?', 'Como os CFCs destruíam a camada de ozônio e quais substâncias os substituíram?']),
  createLesson('g3-qui-b1-l9', 'L9: Nitroderivados e Sulfonados', 'quimica',
    'Nitroderivados têm o grupo -NO₂. O TNT (trinitrotolueno) é explosivo usado em mineração. A nitroglicerina é vasodilatador e explosivo. Compostos sulfonados (-SO₃H) são detergentes modernos (biodegradáveis), usados em xampus e sabão em pó. O Detergente Linear Alquilbenzeno Sulfonado (LAS) é o mais comum no Brasil.',
    ['Por que os detergentes modernos contêm grupos sulfonados em vez dos antigos alcanos ramificados (não biodegradáveis)?', 'Como a TNT é produzida e quais os riscos ambientais de sua utilização em mineração?']),
  createLesson('g3-qui-b1-l10', 'L10: Reações de Adição em Compostos Insaturados', 'quimica',
    'Compostos com duplas ou triplas ligações sofrem reações de adição (incorporam outros átomos na ligação). Adição de H₂ (hidrogenação): transforma óleos vegetais líquidos em gorduras sólidas (margarina). Adição de HX (haloidração): forma halogenetos. Adição de H₂O (hidratação): forma álcoois. Adição de X₂ (halogenação): usado para detectar insaturações.',
    ['Como a hidrogenação parcial de óleos vegetais produz margarina e quais os riscos das gorduras trans?', 'Como o teste com Br₂ é usado para diferenciar compostos saturados de insaturados?']),
  createLesson('g3-qui-b1-l11', 'L11: Reações de Substituição em Orgânicos', 'quimica',
    'Nas reações de substituição, um átomo ou grupo é substituído por outro sem alterar a cadeia carbônica principal. Halogenação de alcanos: R-H + Cl₂ → R-Cl + HCl (luz UV). Nitração do benzeno: C₆H₆ + HNO₃ → C₆H₅NO₂ + H₂O. Sulfonação: C₆H₆ + H₂SO₄ → C₆H₅SO₃H + H₂O.',
    ['Por que a halogenação de alcanos requer luz ultravioleta ou calor para iniciar?', 'Qual a importância industrial da nitração de compostos aromáticos na produção de corantes e explosivos?']),
  createLesson('g3-qui-b1-l12', 'L12: Reações de Eliminação', 'quimica',
    'Nas reações de eliminação, átomos ou grupos são removidos da molécula, formando uma ligação dupla ou tripla. Desidratação de álcoois: C₂H₅OH → CH₂=CH₂ + H₂O (com H₂SO₄ concentrado e calor). Desidroalogenação: remove HX de um halogeneto para formar alceno. São o oposto das reações de adição.',
    ['Como o etanol pode ser desidratado para produzir etileno industrial?', 'Por que a reação de eliminação é o oposto da reação de adição?']),
  createLesson('g3-qui-b1-l13', 'L13: Combustão de Compostos Orgânicos', 'quimica',
    'Combustão completa de hidrocarbonetos: CₙHₘ + O₂ → n CO₂ + (m/2) H₂O. Combustão de álcoois: CₙH₂ₙ₊₁OH + O₂ → CO₂ + H₂O. O etanol emite menos CO₂ por km do que a gasolina. Biodiesel (éster de ácido graxo com metanol) é mais limpo que o diesel mineral e é mandatório no Brasil (B14 = 14% de biodiesel).',
    ['Escreva e balance a equação de combustão completa do etanol (C₂H₅OH).', 'Por que o biodiesel é considerado carbono-neutro ao longo de seu ciclo de vida?']),
  createLesson('g3-qui-b1-l14', 'L14: Bioquímica — Carboidratos', 'quimica',
    'Carboidratos (açúcares) são compostos de C, H e O com fórmula geral (CH₂O)ₙ. Monossacarídeos: glicose, frutose, galactose. Dissacarídeos: sacarose (cana — principal produto do agronegócio do Centro-Oeste), lactose (leite), maltose. Polissacarídeos: amido (reserva energética) e celulose (estrutural) têm mesma fórmula (C₆H₁₀O₅)ₙ mas propriedades distintas.',
    ['Por que amido e celulose têm as mesmas fórmulas moleculares mas propriedades físicas tão diferentes?', 'Como a fermentação da sacarose da cana-de-açúcar produz etanol e CO₂?']),
  createLesson('g3-qui-b1-l15', 'L15: Bioquímica — Lipídios', 'quimica',
    'Lipídios são moléculas apolares ricas em C e H. Triglicerídeos (gorduras e óleos) são ésteres de glicerol + 3 ácidos graxos: saturados (gorduras animais sólidas) ou insaturados (óleos vegetais líquidos). Fosfolipídios formam a membrana celular. Esteroides (colesterol, hormônios sexuais) têm estrutura de anéis fundidos.',
    ['Por que gorduras saturadas são sólidas e gorduras insaturadas (óleos) são líquidas à temperatura ambiente?', 'Qual o papel do colesterol na estrutura da membrana celular e quando ele se torna prejudicial à saúde?']),
  createLesson('g3-qui-b1-l16', 'L16: Bioquímica — Proteínas e Aminoácidos', 'quimica',
    'Proteínas são polímeros de aminoácidos unidos por ligações peptídicas. Os 20 aminoácidos essenciais devem ser obtidos pela dieta; o corpo produz os demais. A estrutura das proteínas tem 4 níveis: primária (sequência de aa), secundária (α-hélice e β-folha), terciária (dobramento 3D) e quaternária (subunidades múltiplas). A desnaturação destrói a estrutura mas não a sequência.',
    ['O que é desnaturação proteica e por que cozinhar o ovo "desnatura" suas proteínas de forma irreversível?', 'Como a sequência de aminoácidos (estrutura primária) determina a forma e função de uma proteína?']),
  createLesson('g3-qui-b1-l17', 'L17: Bioquímica — Ácidos Nucleicos (DNA e RNA)', 'quimica',
    'DNA e RNA são polímeros de nucleotídeos. Cada nucleotídeo tem uma base nitrogenada (A, T/U, G, C), uma pentose (desoxirribose/ribose) e fosfato. No DNA, A emparelha com T e G com C (pontes de H). O DNA é dupla-hélice (Watson e Crick, 1953). RNA é fita simples, participa da síntese proteica (transcrição e tradução).',
    ['Por que as bases nitrogenadas do DNA se emparelham especificamente (A-T e G-C)?', 'Como a estrutura do DNA foi descoberta e qual o papel da cientista Rosalind Franklin nessa descoberta?']),
  createLesson('g3-qui-b1-l18', 'L18: Revisão — Funções Orgânicas e Bioquímica', 'quimica',
    'As funções orgânicas (álcoois, ácidos, ésteres, aminas) e as biomoléculas (carboidratos, lipídios, proteínas, ácidos nucleicos) são a base da Química da vida. Compreender esses grupos funcionais explica desde o funcionamento de medicamentos até os biocombustíveis produzidos no Brasil.',
    ['Identifique os grupos funcionais presentes no aminoácido glicina (NH₂-CH₂-COOH).', 'Como a Química Orgânica conecta o petróleo, os biocombustíveis e as biomoléculas em termos de estrutura e reatividade?']),
];

export const quiLessonsB2: Lesson[] = [
  createLesson('g3-qui-b2-l1', 'L1: Eletroquímica — Revisão e Aprofundamento', 'quimica',
    'Revisão: pilhas (conversão de energia química em elétrica) e eletrólise (conversão de energia elétrica em química). A equação de Nernst calcula a FEM em condições não-padrão: E = E° − (RT/nF)lnQ. A eletroquímica é base das tecnologias de energia renovável: células de combustível e baterias avançadas.',
    ['Como a equação de Nernst explica por que a tensão de uma bateria diminui conforme ela descarrega?', 'Por que a eletroquímica é central para a transição energética e a descarbonização da economia?']),
  createLesson('g3-qui-b2-l2', 'L2: Radioatividade — Conceito e Tipos de Radiação', 'quimica',
    'Núcleos instáveis emitem radiação espontaneamente. Há três tipos: partícula α (núcleo de He, pouco penetrante), partícula β (elétron ou pósitron, penetrância média) e raios γ (onda eletromagnética, alta penetrância). A radioatividade foi descoberta por Henri Becquerel e estudada pelos Curies (os dois únicos a ganharem dois Prêmios Nobel na mesma área).',
    ['Qual o tipo de radiação mais perigoso para o ser humano e por quê?', 'Como Marie Curie descobriu dois novos elementos (polônio e rádio) e qual foi o custo de sua saúde nessa pesquisa?']),
  createLesson('g3-qui-b2-l3', 'L3: Decaimento Radioativo e Meia-Vida', 'quimica',
    'A meia-vida (t₁/₂) é o tempo necessário para que metade dos átomos radioativos de uma amostra se desintegre. É uma constante para cada isótopo. Aplicações: datação por ¹⁴C (arqueologia, fósseis), ²³⁸U (geologia), ²³⁵U (reatores nucleares). A fórmula é: N = N₀ × (1/2)^(t/t₁/₂).',
    ['Se a meia-vida do ¹⁴C é 5730 anos e uma amostra perdeu 75% do ¹⁴C original, quantos anos têm?', 'Como a datação por carbono-14 ajuda arqueólogos a determinar a idade de sítios pré-históricos no Brasil?']),
  createLesson('g3-qui-b2-l4', 'L4: Reações Nucleares — Fissão e Fusão', 'quimica',
    'Fissão nuclear: um núcleo pesado (²³⁵U ou ²³⁹Pu) absorve um nêutron e se divide em dois núcleos menores, liberando energia e mais nêutrons (reação em cadeia). Fusão nuclear: núcleos leves se unem (²H + ³H → ⁴He + n), liberando energia muito maior. O Sol funciona por fusão. Usinas nucleares usam fissão.',
    ['Por que a fusão nuclear produz mais energia que a fissão, mas ainda não é viável comercialmente?', 'Qual o papel das usinas de Angra dos Reis na matriz energética brasileira?']),
  createLesson('g3-qui-b2-l5', 'L5: Energia Nuclear e o Brasil', 'quimica',
    'O Brasil tem as 6ª maiores reservas de urânio do mundo (Minas Gerais, Bahia). A empresa INB (Indústrias Nucleares do Brasil) processa o urânio para as usinas de Angra 1 e 2. O Brasil tem um programa nuclear próprio de enriquecimento de urânio (segredo estratégico). A energia nuclear gera ~2% da eletricidade brasileira com baixíssima emissão de carbono.',
    ['Quais são as vantagens e desvantagens da energia nuclear em relação às fontes renováveis?', 'Por que o enriquecimento de urânio é considerado tecnologia estratégica e como o Brasil desenvolveu essa capacidade?']),
  createLesson('g3-qui-b2-l6', 'L6: Aplicações Médicas da Radioatividade', 'quimica',
    'A medicina nuclear usa radioisótopos para diagnóstico e terapia. PET scan usa ¹⁸F (fluordesoxiglicose) para detectar cânceres e doenças neurológicas. A cintilografia usa ⁹⁹ᵐTc. Radioterapia usa ⁶⁰Co ou ¹⁹²Ir para destruir tumores. O iodomarcado (¹³¹I) trata o câncer de tireoide. O INCA (Instituto Nacional de Câncer) no Brasil usa essas tecnologias.',
    ['Como o PET scan usa radioatividade para localizar tumores no corpo?', 'Por que o iodo radioativo (¹³¹I) é específico para tratar o câncer de tireoide?']),
  createLesson('g3-qui-b2-l7', 'L7: Proteção Radiológica e Acidentes Nucleares', 'quimica',
    'A proteção radiológica usa distância, tempo e blindagem. Doses de radiação são medidas em Sievert (Sv). O acidente de Goiânia (1987) é o maior acidente radiológico da América Latina: uma fonte de ¹³⁷Cs de radioterapia abandonada contaminou centenas de pessoas. Fukushima (2011) mostrou os riscos dos tsunamis para usinas nucleares costeiras.',
    ['O que aconteceu no acidente radiológico de Goiânia em 1987 e quais as lições aprendidas?', 'Quais são os três princípios da proteção radiológica e como eles minimizam a exposição?']),
  createLesson('g3-qui-b2-l8', 'L8: Espectroscopia — RMN e Espectrometria de Massa', 'quimica',
    'A Ressonância Magnética Nuclear (RMN) é usada para determinar estruturas moleculares, baseando-se na absorção de ondas de rádio por núcleos (especialmente ¹H e ¹³C) em campo magnético. A espectrometria de massa fragmente moléculas e mede a razão massa/carga, determinando a massa molecular e a estrutura. Essas técnicas são essenciais em farmacologia e pesquisa.',
    ['Como a RMN é usada para determinar a estrutura de uma molécula orgânica desconhecida?', 'Como a espectrometria de massa pode identificar substâncias em amostras ambientais ou forenses?']),
  createLesson('g3-qui-b2-l9', 'L9: Nanotecnologia e Materiais Avançados', 'quimica',
    'Nanotecnologia manipula a matéria na escala nanométrica (1-100 nm). Nanopartículas de prata têm ação antibacteriana (curativos e tecidos hospitalares). Nanotubos de carbono têm resistência maior que o aço. O grafeno (carbono 2D) tem condutividade elétrica excepcional. O Brasil tem laboratórios de nanotecnologia na USP, Unicamp e outras universidades.',
    ['Por que as nanopartículas de ouro têm cor vermelha, quando o ouro bulk é amarelo?', 'Quais as possíveis aplicações de nanopartículas em medicamentos de liberação controlada?']),
  createLesson('g3-qui-b2-l10', 'L10: Polímeros Avançados e Materiais Compostos', 'quimica',
    'Polímeros de alto desempenho: Kevlar (balístico e à-prova de bala: poliamida aromática), polímeros condutores (como polianilina — Nobel 2000), polímeros biodegradáveis (PHB, produzido por bactérias). Materiais compostos combinam fibra de carbono com resina epóxi para construção de aviões (Embraer) e equipamentos esportivos.',
    ['Por que o Kevlar é mais resistente ao impacto que o aço com menor massa?', 'Como a fibra de carbono + resina epóxi tornou os aviões da Embraer mais eficientes em combustível?']),
  createLesson('g3-qui-b2-l11', 'L11: Química Ambiental — Atmosfera e Poluição', 'quimica',
    'A atmosfera tem camadas: troposfera (clima), estratosfera (ozônio — absorve UV), mesosfera, termosfera. Poluentes primários (emitidos diretamente): CO, NOₓ, SOₓ, VOCs, material particulado. Poluentes secundários (formados na atmosfera): O₃ troposférico, HNO₃ (chuva ácida). No Brasil, a queima de cana e as queimadas no Cerrado são fontes importantes.',
    ['Como os NOₓ emitidos por automóveis contribuem para a formação de ozônio troposférico (smog fotoquímico)?', 'Qual o impacto das queimadas no Cerrado e na Amazônia na qualidade do ar de cidades como Palmas?']),
  createLesson('g3-qui-b2-l12', 'L12: Química Ambiental — Água e Solo', 'quimica',
    'Poluição da água: metais pesados (Hg do garimpo, Pb de tintas antigas), nitratos de fertilizantes (eutrofização), pesticidas e microplásticos. Poluição do solo: agrotóxicos persistentes, metais pesados de mineração, lixiviação. O Brasil tem o maior consumo de agrotóxicos do mundo por hectare, com impactos nos rios e lençóis freáticos do Cerrado.',
    ['Como o uso excessivo de fertilizantes nitrogenados contamina as águas subterrâneas com nitratos?', 'Quais os impactos do mercúrio do garimpo ilegal nos rios e populações indígenas do Tocantins?']),
  createLesson('g3-qui-b2-l13', 'L13: Mudanças Climáticas e Química', 'quimica',
    'Gases de efeito estufa (GEE): CO₂ (queima de combustíveis fósseis), CH₄ (pecuária — o Brasil tem o maior rebanho bovino comercial do mundo, contribuindo com emissões de CH₄), N₂O (fertilizantes) e CFCs. O potencial de aquecimento global (PAG) compara cada GEE ao CO₂. O Brasil é signatário dos Acordos de Paris.',
    ['Por que o metano (CH₄) é mais preocupante que o CO₂ em curto prazo, apesar de emitido em menor quantidade?', 'Quais compromissos o Brasil assumiu no Acordo de Paris e como o desmatamento da Amazônia dificulta seu cumprimento?']),
  createLesson('g3-qui-b2-l14', 'L14: Energias Renováveis — Química da Transição Energética', 'quimica',
    'A transição energética requer novas soluções químicas. Painéis solares fotovoltaicos usam silício ou perovskitas. Biocombustíveis (etanol e biodiesel) são produzidos por reações orgânicas. Hidrogênio verde (eletrólise com energia renovável) não emite CO₂. Baterias de fluxo vanadium armazenam grandes quantidades de energia para a rede elétrica.',
    ['Qual a reação química que ocorre na célula fotovoltaica de silício para converter luz em eletricidade?', 'Por que o Brasil é um dos países com maior potencial para produção de biocombustíveis e energia solar?']),
  createLesson('g3-qui-b2-l15', 'L15: Indústria Farmacêutica e Síntese de Medicamentos', 'quimica',
    'Medicamentos são substâncias que interagem com receptores do corpo para tratar doenças. A Aspirina (ácido acetilsalicílico) é sintetizada por acetilação do ácido salicílico. Antibióticos como penicilinas têm estrutura de anel β-lactâmico. A Fiocruz e o Instituto Butantan (Brasil) produzem vacinas e medicamentos essenciais para o SUS.',
    ['Como a penicilina destrói bactérias em nível molecular?', 'Por que a produção nacional de medicamentos (como a Fiocruz faz) é estratégica para a soberania sanitária do Brasil?']),
  createLesson('g3-qui-b2-l16', 'L16: Cosméticos e Química no Cotidiano', 'quimica',
    'Sabão (saponificação de gorduras: base + éster → sabão + glicerol) vs. detergente (surfactante sintético sulfonado — biodegradável). Perfumes: misturas de ésteres, aldeídos e álcoois aromáticos. Protetor solar: filtros UV químicos (octilmetoxicinamato) e físicos (ZnO, TiO₂). Esmaltes: polímeros nitrocelulose + plastificante. A indústria cosmética brasileira (Natura, O Boticário) é das maiores do mundo.',
    ['Qual a diferença química entre sabão e detergente e por que os detergentes modernos são biodegradáveis?', 'Como os protetores solares atuam quimicamente para proteger a pele da radiação UV?']),
  createLesson('g3-qui-b2-l17', 'L17: Agroquímica e Produção de Alimentos', 'quimica',
    'Fertilizantes: nitrogenados (ureia, sulfato de amônio), fosfatados (superfosfato), potássicos (KCl). O Brasil é o maior importador de fertilizantes do mundo — dependência estratégica. Agrotóxicos: inseticidas (organofosforados, piretroides), herbicidas (glifosato), fungicidas. A Embrapa desenvolve tecnologias para agricultura tropical brasileira com menor uso de insumos químicos.',
    ['Por que o Brasil tem dependência de importações de fertilizantes e quais os riscos para a segurança alimentar?', 'Quais as alternativas ao glifosato (herbicida mais usado no Brasil) sendo desenvolvidas pela pesquisa agronômica?']),
  createLesson('g3-qui-b2-l18', 'L18: Revisão Final — Química Orgânica e Ambiental', 'quimica',
    'A Química Orgânica está em tudo: medicamentos, combustíveis, alimentos, materiais. A Química Ambiental mostra as consequências das decisões industriais no planeta. A radioatividade tem aplicações médicas e energéticas, mas também riscos. O profissional de Química tem papel central na transição para uma economia sustentável.',
    ['Como a Química pode contribuir para um modelo de desenvolvimento mais sustentável no Brasil?', 'Quais são as maiores oportunidades de carreira para um químico no Brasil atual?']),
];

export const quiLessonsB3: Lesson[] = [
  createLesson('g3-qui-b3-l1', 'L1: Revisão Integrada ENEM — Química Geral', 'quimica',
    'O ENEM testa a Química de forma contextualizada e interdisciplinar, exigindo aplicação do conhecimento em situações reais. Temas frequentes: funções orgânicas (etanol, sabão, plásticos), reações (combustão, oxidação), soluções e misturas, elementos da tabela periódica em contexto. A maioria das questões traz texto introdutório com informações.',
    ['Como estratégia de ENEM, como você aborda uma questão de Química com texto longo?', 'Por que o conhecimento de funções orgânicas é central para as questões de Química do ENEM?']),
  createLesson('g3-qui-b3-l2', 'L2: ENEM — Química dos Alimentos', 'quimica',
    'Questões sobre alimentos no ENEM abordam: aditivos alimentares (conservantes, corantes, antioxidantes), vitaminas (estrutura química de vitamina C — ácido ascórbico, vitamina A — retinol), fermentação, lipídios trans, gordura saturada, açúcares. O rótulo nutricional é fonte de dados química contextualizada.',
    ['Por que o ácido ascórbico (vitamina C) funciona como antioxidante conservando alimentos?', 'Como você interpretaria a tabela nutricional de um alimento para identificar seus compostos químicos?']),
  createLesson('g3-qui-b3-l3', 'L3: ENEM — Química e Energia', 'quimica',
    'Temas de energia frequentes no ENEM: combustíveis fósseis vs. renováveis (etanol, biodiesel, H₂), pilhas e baterias (cálculo de FEM, lei de Faraday), energia nuclear (fissão, meia-vida, equação nuclear), termoquímica (reações exo e endotérmicas aplicadas). Relacionar energia e reações químicas com impactos sociais e ambientais.',
    ['Qual a relação entre a entalpia de combustão de um combustível e sua eficiência energética?', 'Como as questões de ENEM integram Química, Física e ciências ambientais ao tratar de energia?']),
  createLesson('g3-qui-b3-l4', 'L4: ENEM — Química e Meio Ambiente', 'quimica',
    'Questões ambientais do ENEM: efeito estufa (CO₂, CH₄, N₂O), buraco na camada de ozônio (CFCs), chuva ácida (SOₓ, NOₓ), poluição das águas (metais pesados, nitratos, agrotóxicos), reciclagem de materiais (plásticos, metais, vidro, papel), tratamento de esgoto.',
    ['Como os CFCs destroem o ozônio estratosférico em nível molecular (reação em cadeia)?', 'Como interpretar uma questão do ENEM que pede para relacionar química industrial com impacto ambiental?']),
  createLesson('g3-qui-b3-l5', 'L5: ENEM — Química e Saúde', 'quimica',
    'Tópicos de saúde no ENEM: antibióticos (como funcionam), antiácidos (reação de neutralização), analgésicos (estrutura da aspirina), vacinas (Química da imunologia), hormônios (estrutura de esteroides), vitaminas, minerais essenciais. Relacionar estrutura química com ação biológica.',
    ['Como o ibuprofeno (anti-inflamatório) age no corpo em nível molecular?', 'Por que é importante manter os esquemas de vacinação completos e como as vacinas funcionam imunologicamente?']),
  createLesson('g3-qui-b3-l6', 'L6: ENEM — Polímeros e Materiais', 'quimica',
    'Questões sobre polímeros no ENEM: identificação do monômero, tipo de polimerização (adição ou condensação), propriedades e usos (PET, PE, PVC, nylon, borracha). Reciclagem de plásticos (os 7 códigos). Bioplásticos e materiais sustentáveis. Propriedades dos materiais: condutividade, dureza, flexibilidade relacionadas com a estrutura.',
    ['Como identificar o tipo de polimerização (adição ou condensação) pelo monômero?', 'Qual polímero do cotidiano tem estrutura de adição e qual tem estrutura de condensação?']),
  createLesson('g3-qui-b3-l7', 'L7: ENEM — Soluções e Cálculos', 'quimica',
    'Questões de cálculo no ENEM são interpretativas mas exigem cálculo de: concentração (g/L, molaridade), diluição (M₁V₁ = M₂V₂), pH de ácidos e bases fortes, estequiometria simples. O ENEM disponibiliza tabela periódica. Questões trazem contexto: rótulo de produto, bula de medicamento, dosagem industrial.',
    ['Como calcular a concentração de um medicamento em solução para determinar a dosagem correta?', 'Em qual contexto real você precisaria calcular uma diluição usando M₁V₁ = M₂V₂?']),
  createLesson('g3-qui-b3-l8', 'L8: ENEM — Radioatividade e Medicina Nuclear', 'quimica',
    'Questões de radioatividade no ENEM: equações nucleares balanceadas (conservação de A e Z), meia-vida e datação, identificação de tipos de radiação (α, β, γ), aplicações médicas (PET, cintilografia, radioterapia), riscos da radiação, acidentes nucleares históricos (Chernobyl, Fukushima, Goiânia).',
    ['Balance a equação de decaimento alfa do ²³⁸U: ²³⁸U → ? + ⁴He.', 'Como a meia-vida de um radioisótopo determina sua aplicação médica ou industrial?']),
  createLesson('g3-qui-b3-l9', 'L9: Resolução de Questões ENEM — Química Orgânica', 'quimica',
    'Química Orgânica no ENEM: identificação de funções orgânicas por grupos funcionais, isomeria (plana e geométrica), reações orgânicas (esterificação, saponificação, combustão, adição), polímeros, bioquímica (carboidratos, lipídios, proteínas, ácidos nucleicos). O contexto é sempre social, ambiental ou de saúde.',
    ['Numa questão de ENEM sobre sabão artesanal, como você identificaria os reagentes e produtos da saponificação?', 'Como diferenciar um ácido carboxílico de um éster pela fórmula estrutural em uma questão?']),
  createLesson('g3-qui-b3-l10', 'L10: Simulado ENEM — Questões Comentadas I', 'quimica',
    'Resolução comentada de questões reais do ENEM sobre: separação de misturas (garimpo e flotação), ligações químicas (polares e apolares em emulsões), tabela periódica (propriedades periódicas aplicadas), soluções (concentração e efeito coligativo). Estratégia: ler o enunciado, identificar o tema, aplicar o conceito.',
    ['Qual estratégia você usa para resolver uma questão de Química do ENEM que você nunca viu?', 'Por que o ENEM raramente pede cálculos complexos mas exige muito raciocínio contextualizado?']),
  createLesson('g3-qui-b3-l11', 'L11: Simulado ENEM — Questões Comentadas II', 'quimica',
    'Resolução de questões sobre: reações eletroquímicas (corrosão, pilhas), termoquímica (entalpia e combustíveis), cinética (fatores de velocidade), equilíbrio (Le Chatelier em contexto industrial). Cada questão exige integração de conceitos com interpretação de gráficos, tabelas e textos científicos.',
    ['Como interpretar um gráfico de velocidade de reação vs. temperatura para extrair informações úteis?', 'Em uma questão sobre Le Chatelier na síntese da amônia, quais fatores industriais devem ser considerados?']),
  createLesson('g3-qui-b3-l12', 'L12: Química e Tecnologia — Inovação Brasileira', 'quimica',
    'O Brasil tem importantes centros de pesquisa química: LNLS (Luz Síncrotron em Campinas — permite ver estruturas de moléculas), CBMM (maior produtor mundial de nióbio — metal usado em ligas especiais), Embrapa (pesquisa em agroquímica sustentável), Petrobras (pré-sal, refino e biocombustíveis). A pesquisa química brasileira tem relevância global.',
    ['O que é o Síncrotron e como ele é usado para determinar estruturas moleculares?', 'Por que o nióbio brasileiro é chamado de "metal do futuro" e onde ele é aplicado?']),
  createLesson('g3-qui-b3-l13', 'L13: Química e Cidadania — Consumo Consciente', 'quimica',
    'O conhecimento químico permite escolhas conscientes: ler rótulos de alimentos (identificar aditivos, conservantes, corantes artificiais), escolher produtos de limpeza mais seguros, entender riscos de medicamentos, preferir produtos orgânicos e com menor pegada de carbono. Química é ferramenta de cidadania e autonomia.',
    ['Como o conhecimento de química ajuda você a fazer escolhas mais conscientes de consumo?', 'Por que o rótulo "sem conservantes" em alimentos não significa necessariamente que o produto é mais saudável?']),
  createLesson('g3-qui-b3-l14', 'L14: Revisão — Ligações Químicas e Propriedades', 'quimica',
    'Revisão final: ligações iônicas (NaCl — cristais solúveis, boa condutividade em solução), covalentes (H₂O — pontes de hidrogênio, alto ponto de ebulição), metálicas (Fe — condutividade e maleabilidade). Polaridade e geometria molecular determinam as propriedades. Forças intermoleculares explicam o comportamento físico das substâncias.',
    ['Como o tipo de ligação química de uma substância determina seu ponto de fusão?', 'Por que substâncias com pontes de hidrogênio têm pontos de ebulição anormalmente elevados?']),
  createLesson('g3-qui-b3-l15', 'L15: Revisão — Estequiometria e Soluções', 'quimica',
    'Revisão completa de cálculos: mol e massa molar, relações estequiométricas, reagente limitante, rendimento, pureza, concentração (g/L e molaridade), diluição, propriedades coligativas. O domínio do cálculo estequiométrico é fundamental para o ENEM e para qualquer curso superior de saúde, engenharia ou ciências.',
    ['Quais os passos obrigatórios para resolver qualquer problema estequiométrico?', 'Qual tipo de cálculo de Química mais aparece no ENEM e qual é a melhor estratégia de resolução?']),
  createLesson('g3-qui-b3-l16', 'L16: Revisão — Funções Inorgânicas e Reações', 'quimica',
    'Revisão: ácidos (pH < 7, liberam H⁺), bases (pH > 7, liberam OH⁻), sais (íons positivos e negativos), óxidos (binários com O). Reações: síntese, análise, deslocamento, dupla troca, neutralização, combustão, precipitação, redox. Aplicações industriais e cotidianas de cada tipo de reação.',
    ['Dado: NaOH + H₂SO₄ → ? Identifique o tipo de reação e os produtos formados.', 'Como o conhecimento das funções inorgânicas é aplicado no tratamento da acidez do solo agrícola do Cerrado?']),
  createLesson('g3-qui-b3-l17', 'L17: Revisão — Química Orgânica Completa', 'quimica',
    'Revisão das funções orgânicas: álcoois, fenóis, éteres, aldeídos, cetonas, ácidos carboxílicos, ésteres, aminas, amidas. Isomeria (plana e espacial). Reações orgânicas principais. Polímeros (adição e condensação). Bioquímica (carboidratos, lipídios, proteínas, DNA/RNA). Todas essas conexões aparecem no ENEM e no vestibular.',
    ['Crie um mapa mental conectando etanol, ácido acético, éster e saponificação em uma cadeia de reações.', 'Por que o ENEM contextualiza questões de orgânica com saúde, alimentos e sustentabilidade ambiental?']),
  createLesson('g3-qui-b3-l18', 'L18: Avaliação Final — Integração e Projeções', 'quimica',
    'A Química do Ensino Médio oferece base para inúmeras carreiras: Química, Engenharia Química, Farmácia, Medicina, Agronomia, Ciências Ambientais e Geologia. A Química está no centro dos maiores desafios da humanidade: transição energética, segurança alimentar, saúde pública e combate às mudanças climáticas.',
    ['Como os conhecimentos de Química que você aprendeu no EM podem contribuir para resolver desafios do Brasil no século XXI?', 'Quais áreas da Química mais te interessam e por quê?']),
];

export const quiLessonsB4: Lesson[] = [
  createLesson('g3-qui-b4-l1', 'L1: Revisão Geral — Química da 1ª Série', 'quimica',
    'Revisão integrada: matéria e propriedades, separação de misturas, modelos atômicos, tabela periódica, ligações químicas, funções inorgânicas e estequiometria básica. A base construída na 1ª série é o alicerce para toda a Química do EM. Identificar e preencher lacunas nessa base garante melhor desempenho no ENEM.',
    ['Quais conceitos da 1ª série você ainda tem dificuldades e como planeja revisá-los antes do ENEM?', 'Desenhe um mapa conceitual conectando: átomo → ligação química → função inorgânica → reação química.']),
  createLesson('g3-qui-b4-l2', 'L2: Revisão Geral — Química da 2ª Série', 'quimica',
    'Revisão integrada: soluções (concentração, diluição, coligativas), termoquímica (entalpia, Hess), cinética (velocidade, fatores, catálise), equilíbrio (Le Chatelier, Ka, Kb, Kps, pH), eletroquímica (pilhas, eletrólise, Faraday). Esses temas são os mais cobrados no ENEM de Química.',
    ['Qual a relação entre termoquímica, cinética e equilíbrio químico no conceito de reação espontânea?', 'Como Le Chatelier pode explicar desde a produção industrial de amônia até o equilíbrio do CO₂ no sangue?']),
  createLesson('g3-qui-b4-l3', 'L3: Revisão Geral — Química Orgânica', 'quimica',
    'Revisão integrada de Química Orgânica: funções (alcanos, alcenos, áreis, álcoois, ácidos, ésteres, aminas, amidas), isomeria, reações (adição, substituição, eliminação, condensação), polímeros, bioquímica. A Química Orgânica representa ~40% das questões de Química no ENEM.',
    ['Qual a função orgânica presente no paracetamol (acetaminofeno) e como você a identifica?', 'Como a estrutura do DNA (ácido nucleico) se relaciona com os conceitos de bases nitrogenadas e ligações de hidrogênio?']),
  createLesson('g3-qui-b4-l4', 'L4: Questões Comentadas — ENEM 2019-2023', 'quimica',
    'Resolução comentada de questões selecionadas do ENEM 2019 a 2023 abrangendo os principais temas: combustíveis e meio ambiente, estrutura atômica, soluções e indústria, polímeros e plásticos, eletroquímica e pilhas. Análise das competências avaliadas e estratégias de resolução.',
    ['Que padrões você identifica nas questões de Química do ENEM dos últimos anos?', 'Como o ENEM integra conhecimentos de Química com contextos sociais e ambientais brasileiros?']),
  createLesson('g3-qui-b4-l5', 'L5: Simulado Final I — Questões de Múltipla Escolha', 'quimica',
    'Simulado com 10 questões no formato ENEM cobrindo: separação de misturas, funções orgânicas, estequiometria, equilíbrio ácido-base, eletroquímica, polímeros, radioatividade, bioquímica e questões interdisciplinares. Resolução cronometrada (2 minutos por questão) e análise dos erros.',
    ['Quais questões do simulado você errou e por quê?', 'Como gerenciar o tempo nas questões de Química do ENEM sem deixar nenhuma em branco?']),
  createLesson('g3-qui-b4-l6', 'L6: Simulado Final II — Questões Discursivas', 'quimica',
    'Resolução de questões discursivas no formato ENEM/vestibular sobre Química: explicar por que uma reação é espontânea, descrever como funciona uma pilha, calcular pH, balancear equação nuclear. A resposta deve ser clara, usar terminologia química correta e relacionar o conceito com o contexto dado.',
    ['Como estruturar uma resposta discursiva clara e completa para uma questão de Química?', 'Qual a diferença entre descrever um processo químico e apenas nomear as substâncias envolvidas?']),
  createLesson('g3-qui-b4-l7', 'L7: Carreiras em Química — Perspectivas Profissionais', 'quimica',
    'Carreiras com base em Química: Química (bacharelado/licenciatura), Engenharia Química, Farmácia, Bioquímica, Medicina, Odontologia, Nutrição, Agronomia, Geologia, Ciências Ambientais. O mercado de trabalho inclui indústria química, farmacêutica, alimentos, petróleo, mineração, laboratórios clínicos e pesquisa acadêmica. Salários e oportunidades no Brasil.',
    ['Quais cursos superiores têm Química como disciplina central e quais áreas de atuação profissional oferecem?', 'Como o domínio de Química pode abrir oportunidades profissionais no agronegócio do Tocantins?']),
  createLesson('g3-qui-b4-l8', 'L8: Química no Cotidiano — Aplicações Práticas', 'quimica',
    'Química no dia a dia: culinária (reações de Maillard na fritura, gelatinização do amido), cosméticos (shampoo, batom, perfume), limpeza (sabão, alvejante — hipoclorito de sódio), medicamentos OTC (analgésicos, antiácidos, vitaminas), embalagens (plásticos, papel alumínio). Identificar Química no cotidiano reforça o aprendizado.',
    ['Quais reações químicas ocorrem quando você cozinha um ovo?', 'Como o hipoclorito de sódio (água sanitária) mata micro-organismos em nível molecular?']),
  createLesson('g3-qui-b4-l9', 'L9: Química e Desenvolvimento Sustentável', 'quimica',
    'A Química Verde propõe 12 princípios para produção sustentável: prevenção de resíduos, eficiência atômica, síntese menos perigosa, design de produtos seguros, solventes mais seguros, eficiência energética, matérias-primas renováveis, derivatização desnecessária, catálise, degradabilidade, monitoramento em tempo real e química mais segura.',
    ['Como a Química Verde pode transformar a indústria química brasileira para um modelo mais sustentável?', 'Cite um exemplo de aplicação dos princípios da Química Verde já implementado no Brasil.']),
  createLesson('g3-qui-b4-l10', 'L10: Integração Interdisciplinar — Química, Biologia e Física', 'quimica',
    'A fronteira entre Química, Biologia e Física é cada vez mais tênue. Bioquímica estuda as reações nos seres vivos. Biofísica estuda processos físicos nas células. A Física Quântica explica as ligações químicas. O ENEM reflete essa interdisciplinaridade: muitas questões integram conceitos de duas ou três ciências.',
    ['Dê um exemplo de fenômeno que só pode ser explicado com conceitos de Química E Biologia E Física simultaneamente.', 'Como o estudo da Química prepara você para entender os desafios científicos do século XXI?']),
  createLesson('g3-qui-b4-l11', 'L11: Revisão Final — Tabela Periódica e Ligações', 'quimica',
    'Revisão definitiva: tabela periódica (tendências de raio, eletronegatividade, energia de ionização), ligações (iônica, covalente, metálica), polaridade e geometria molecular, forças intermoleculares. Esses conceitos fundamentam todo o restante da Química e aparecem direta ou indiretamente em muitas questões do ENEM.',
    ['Por que o flúor é o elemento mais eletronegativo e como isso afeta as moléculas que ele forma?', 'Como a geometria molecular da água (angular) está relacionada com suas propriedades físicas únicas?']),
  createLesson('g3-qui-b4-l12', 'L12: Revisão Final — Funções Inorgânicas', 'quimica',
    'Revisão: ácidos (pH, força, nomenclatura), bases (pH, força, nomenclatura), sais (formação, hidrólise, solubilidade), óxidos (ácidos, básicos, anfóteros, neutros). Reações entre funções: neutralização, formação de óxidos, dissolução. Aplicações em saúde, agricultura e indústria.',
    ['Explique em suas palavras por que misturar ácido e base produz sal e água.', 'Como o pH ácido do solo do Cerrado afeta a disponibilidade de nutrientes para as plantas?']),
  createLesson('g3-qui-b4-l13', 'L13: Revisão Final — Estequiometria', 'quimica',
    'Revisão completa de estequiometria: massa molar, conversão mol-grama-partícula-litro, equações balanceadas, proporção estequiométrica, reagente limitante, excesso, rendimento, pureza, volume de gás (CNTP e pela equação de gás ideal). O domínio estequiométrico é o maior diferencial para questões quantitativas do ENEM.',
    ['Dado que 100g de CaCO₃ são aquecidos (CaCO₃ → CaO + CO₂), com 80% de rendimento, quantos litros de CO₂ (CNTP) são produzidos?', 'Por que a estequiometria é chamada de "a contabilidade da Química"?']),
  createLesson('g3-qui-b4-l14', 'L14: Revisão Final — Soluções e Propriedades Coligativas', 'quimica',
    'Revisão: concentração (g/L, molaridade, %), diluição, misturas, solubilidade, propriedades coligativas (ebulhoscopia, crioscopia, osmometria). O significado físico de cada propriedade coligativa e suas aplicações: anticongelante em carros, dessalinização, soro fisiológico, processos de conservação de alimentos.',
    ['Por que o etanol (anticongelante) é adicionado ao radiador do carro no inverno e como isso altera o ponto de congelamento?', 'Explique como a osmose reversa pode transformar água do mar em água potável.']),
  createLesson('g3-qui-b4-l15', 'L15: Revisão Final — Termoquímica e Cinética', 'quimica',
    'Revisão: entalpia (exo e endotérmicas), Lei de Hess, energias de ligação, cinética (velocidade, fatores, lei da velocidade, energia de ativação), catálise. A compreensão de como a energia se transforma nas reações químicas é fundamental para o ENEM e para compreender a eficiência de processos industriais e biológicos.',
    ['Como a Lei de Hess permite calcular a entalpia de uma reação que não pode ser medida diretamente?', 'Por que os catalisadores enzimáticos do corpo humano são tão eficientes em reduzir a energia de ativação?']),
  createLesson('g3-qui-b4-l16', 'L16: Revisão Final — Equilíbrio e Eletroquímica', 'quimica',
    'Revisão: equilíbrio químico (Kc, Kp, Le Chatelier), equilíbrio ácido-base (Ka, Kb, pH, tampões), Kps, eletroquímica (pilhas, eletrólise, Nernst, Faraday, corrosão). Esses temas são muito cobrados no ENEM e em vestibulares de medicina e engenharia.',
    ['Como a constante de equilíbrio Kc e a FEM de uma pilha estão matematicamente relacionadas?', 'Por que a produção de alumínio por eletrólise requer uma fonte constante de energia elétrica de alta potência?']),
  createLesson('g3-qui-b4-l17', 'L17: Revisão Final — Orgânica e Bioquímica', 'quimica',
    'Revisão: funções orgânicas, isomeria, reações orgânicas, polímeros, bioquímica (carboidratos, lipídios, proteínas, ácidos nucleicos). A Química Orgânica explica desde os combustíveis que movem o Brasil até as moléculas que sustentam a vida. É o tema mais interdisciplinar com a Biologia no ENEM.',
    ['Como a fermentação alcoólica da glicose (C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂) se encaixa no ciclo do carbono e na bioenergia?', 'Explique por que a bioquímica é o ponto de convergência entre Química e Biologia.']),
  createLesson('g3-qui-b4-l18', 'L18: Avaliação Final — Química do Ensino Médio', 'quimica',
    'Conclusão da jornada pela Química do Ensino Médio: da estrutura da matéria (átomos e ligações) às transformações químicas (reações), passando pelas soluções e equilíbrios, chegando à Química Orgânica e às conexões com biologia, física, meio ambiente e sociedade. O aprendizado de Química é uma conquista intelectual para a vida.',
    ['Como os conceitos de Química se interconectam numa grande "rede" do conhecimento?', 'De que forma o estudo da Química mudou sua forma de enxergar o mundo ao seu redor?']),
];
