
export const STUDENTS_SEED_DATA = [
  { name: "Lyandra Alves Marques", email: "lyandraalvesmarques@gmail.com", password: "lyaepi@1", school_class: "33.06" },
  { name: "Morgana da Rocha Lopes da Silva", email: "mrochalopessilva@gmail.com", password: "123456", school_class: "33.08" },
  { name: "Letícia Isabel Pereira da Silva", email: "leticiaisabelp.silva18@gmail.com", password: "18092008Let", school_class: "33.01" },
  { name: "Isabela Geovana Fagundes Delazzeri", email: "isabelafagundes734@gmail.com", password: "Isa230309@", school_class: "33.09" },
  { name: "Laura Lohara Monteiro Assunção", email: "lauralohara21@gmail.com", password: "Brunalauraarthur21", school_class: "33.08" },
  { name: "Ana clara Pereira dos Santos Leite", email: "anaclarapeite2023@gmail.com", password: "anaclara2008*", school_class: "33.07" },
  { name: "Ana Beatriz Alves lima", email: "anabeatrizalveslima686@gmail.com", password: "beatriz12", school_class: "33.08" },
  { name: "Anna Júlia Cavalcante Borges", email: "cavalcanteannajulia8@gmail.com", password: "annajuli.12", school_class: "23.03" },
  { name: "Isabella Portilho", email: "isabellaportilhoj@gmail.com", password: "21250117", school_class: "33.02" },
  { name: "Isabella Vitoria Araujo Silva", email: "isabelaaraujoesilva4@gmail.com", password: "Baguxu1a", school_class: "23.02" },
  { name: "Ana Luisa Brandão", email: "analuisarodriguesb@gmail.com", password: "Analu3476", school_class: "33.07" },
  { name: "Lara Carvalho de Oliveira", email: "larajapinha27@gmail.com", password: "Lar@27", school_class: "33.09" },
  { name: "Iasmin rosa celestino", email: "celestino.iasrc07@gmail.com", password: "01051218", school_class: "33.04" },
  { name: "Victor Emanoel De Souza Almeida", email: "victor.cpx.trem@gmail.com", password: "18022009 V", school_class: "33.05" },
  { name: "Wanessa Guedes Narciso", email: "wanessaguedesnarciso09@gmail.com", password: "Luaaa009.", school_class: "33.02" },
  { name: "D’Ávila Cristina Parentes dos Santos", email: "davilaparentes@gmail.com", password: "parentes09", school_class: "33.04" },
  { name: "Ezequiel Pereira Maia", email: "maiaezequiel684@gmail.com", password: "22072008Ez.", school_class: "33.06" },
  { name: "Bruna Clay Silva De Jesus Soares", email: "klaybrunad@icloud.com", password: "klay1327", school_class: "33.03" },
  { name: "Nayra", email: "nayra4672@gmail.com", password: "1234", school_class: "23.01" },
  { name: "Isabelly Cecilia", email: "isasousa1805@icloud.com", password: "isabelly18", school_class: "23.02" },
  { name: "CAUA OLIVEIRA DA LUZ ALENCAR", email: "cauaoliveiraa174@gmail.com", password: "571314", school_class: "33.04" },
  { name: "João Pedro Oliveira Alves", email: "jpkff2022@icloud.com", password: "27/09Mae", school_class: "33.05" },
  { name: "Wellika Vitoria De Souza Nunes", email: "wellikavit@icloud.com", password: "Wellika07", school_class: "33.04" },
  { name: "Natalia Costa Fernandes", email: "costafernandesnatalia2@gmail.com", password: "26102009n", school_class: "23.01" },
  { name: "Arthur Fernandes Siqueira", email: "arthurf2215@gmail.com", password: "@Puskasneymar2011", school_class: "23.02" },
  { name: "Geovana Rodrigues vitor Ribeiro", email: "geovanarodriguesvitor@gmail.com", password: "123456", school_class: "23.04" },
  { name: "Matheus da Silva Coutinho", email: "matheusdasilvacoutinho@gmail.com", password: "bela2580", school_class: "33.07" },
  { name: "Kerlon Rodrigues Marques", email: "mcell9175@gmail.com", password: "kerlon103", school_class: "33.02" },
  { name: "Joao Francisco", email: "joaojrrr2009@icloud.com", password: "Larissa0709", school_class: "13.07" },
  { name: "João pedro cerqueira", email: "jp.cerqueiracosta@gmail.com", password: "12junho2008", school_class: "33.06" },
  { name: "Maria Eduarda Louzeiro Nascimento", email: "mlouzeironascimento12@gmail.com", password: "Maria#15", school_class: "33.02" },
  { name: "Lucas Silva Brito", email: "lucas.s.brito127@gmail.com", password: "02112008", school_class: "33.08" },
  { name: "Kaleo Andril de Sousa Vaz", email: "kaleoandril547@gmail.com", password: "13051799", school_class: "33.06" },
  { name: "Calebe Almeida de Araújo", email: "calebe.a.araujo@aluno.senai.br", password: "PET2DZ8W", school_class: "13.06" },
  { name: "Anna Celha Estevão Pereira", email: "annacelha456@gmail.com", password: "120126", school_class: "33.02" },
  { name: "Helena da Silva Martins de Castro", email: "perolasdehelena@gmail.com", password: "pazhelena", school_class: "33.01" },
  { name: "Beatriz Gouvêa Martins", email: "beatrizmartons110@gmail.com", password: "Bia010709", school_class: "23.04" },
  { name: "Mariana Lima do Nascimento", email: "dayananascimento.ascom@gmail.com", password: "Mari@1304", school_class: "23.05" },
  { name: "Ester Oliveira", email: "esuterusama15@gmail.com", password: "Niju", school_class: "23.05" },
  { name: "Sammy dos santos Ferreira", email: "sammysf025@gmail.com", password: "teste123-2014", school_class: "33.04" },
  { name: "Heitor Sardinha", email: "heitor.sardinha64285@gmail.com", password: "heitor1411", school_class: "33.09" },
  { name: "Isadora gomes silva", email: "isadorapgomes@icloud.com", password: "isa4026", school_class: "33.03" },
  { name: "Krishna Weslen dos santos faustino", email: "krishinawf@gmail.com", password: "17112009", school_class: "23.03" },
  { name: "Larissa Neiva Dos Santos", email: "larissaneivadossantos@gmail.com", password: "EhCL231@", school_class: "23.02" },
  { name: "Arthur Almeida Alves", email: "arthuralmeidaalvespmw@gmail.com", password: "arthur02092009", school_class: "23.01" },
  { name: "Natanael Gomes Dias", email: "nataneldias974@gmail.com", password: "senha", school_class: "23.03" },
  { name: "Júlia Victoria da Silva Nobre", email: "juliavictoriadasilvanobre@gmail.com", password: "241316", school_class: "23.02" },
  { name: "Geovana dos Santos Araújo", email: "gs3543310@gmail.com", password: "@Geovanaofc02.", school_class: "33.02" },
  { name: "João Eduardo Rodrigues Rodolfo", email: "jrodriguesrodolfo644@gmail.com", password: "joao123hhJ", school_class: "23.03" },
  { name: "Samyra Silva Santos", email: "samyrasantos0506@gmail.com", password: "20092008", school_class: "23.04" },
  { name: "Vivian gonzaga maia", email: "viviangonzaga@gmail.com", password: "92447868@vivian", school_class: "23.04" },
  { name: "Alicia Irene Braga Da silva", email: "bragaaliciairene@gmail.com", password: "1403209b", school_class: "23.05" },
  { name: "Kallyca Rocha", email: "geruskarochak@gmail.com", password: "Kgrocha13", school_class: "33.05" },
  { name: "Vitória stefane", email: "vitoriastefane2010@gmail.com", password: "20100220", school_class: "23.02" },
  { name: "Marco Antônio Ribeiro Spegiorin", email: "marcoaspegiorin@gmail.com", password: "22143021", school_class: "33.04" },
  { name: "Emanuelli Botelho de Morais", email: "emanuellibotelhosm14@gmail.com", password: "Manu1411&", school_class: "33.06" },
  { name: "Bruno gabriel alencar mendes", email: "brunogab0707@gmail.com", password: "brunin07", school_class: "13.01" },
  { name: "Yasmin Melo Jadão Almeida", email: "yasminmeloja@gmail.com", password: "Mmk03022009@", school_class: "33.02" },
  { name: "Maria Eduarda de souza e silva", email: "marcosalessandro0814@gmail.com", password: "Cenxyf-wahvo2-wosvor", school_class: "13.07" },
  { name: "Ana Clara Rodrigues Sousa", email: "aclara.rodriguessousa@gmail.com", password: "ars276415", school_class: "23.06" },
  { name: "Maria Vitória Teixeira de souza", email: "mariavitoriateixeiradesouza6@gmail.com", password: "12032009", school_class: "33.07" },
  { name: "Arthur Alves da Silva", email: "alvesarthuralvesdasilva084@gmail.com", password: "arthur123", school_class: "23.01" },
  { name: "Julio Cesar Ferreira Rodrigues", email: "juliocfrodrigues5@gmail.com", password: "123456", school_class: "23.02" },
  { name: "Kauane de Oliveira Ribeiro da Silva", email: "aneribeiro446@gmail.com", password: "05Ane2009", school_class: "33.01" },
  { name: "Matheus Da Silva Coutinho", email: "matheusdasilvacoutinho405@gmail.com", password: "Bela2580", school_class: "33.07" },
  { name: "Rosa linda", email: "teixeirarosalinda99@gmail.com", password: "rosacostarf", school_class: "33.08" },
  { name: "Luyz Fernando Alves de Sousa", email: "luyzfernandoalvesdesousa@gmail.com", password: "09092010", school_class: "23.02" },
  { name: "Kélyta Marinho Silva", email: "kelytamarinho10@gmail.com", password: "kelyta2008", school_class: "33.02" },
  { name: "Lucas P. Dantas", email: "lucaspdantas2008@gmail.com", password: "1201103", school_class: "33.04" },
  { name: "Kamilly Martins Lopes", email: "kamillymartinslopes479@gmail.com", password: "K21a22k26", school_class: "33.01" },
  { name: "Samira Pereira da Silva", email: "samirapdasilva@gmail.com", password: "03052008", school_class: "33.01" },
  { name: "Camile Cavalcante Ribeiro", email: "millieyxxx12@gmail.com", password: "Milliey90@", school_class: "33.02" },
  { name: "Ana Clara Domingues Alves da Silva", email: "wwiltonjunior4612@gmail.com", password: "anaHevellyn@22", school_class: "23.06" },
  { name: "Larissa thayla", email: "larissathaylaa@gmail.com", password: "sezhab-nabfuj-poxrE6", school_class: "13.02" },
  { name: "Maria Rita Luz Passos", email: "mariaritaluzpassos@gmail.com", password: "03042009", school_class: "23.01" },
  { name: "Kélyta Marinho", email: "kelytamarinho23@gmail.com", password: "kelyta223", school_class: "33.02" },
  { name: "GUSTAVO FELIPE LIMA RIBEIRO", email: "detetivebatata2@gmail.com", password: "SYBAUgames777", school_class: "13.07" },
  { name: "Gustavo de Sousa da conceição", email: "gugasousa1404@gmail.com", password: "GUGA011", school_class: "13.07" },
  { name: "Rickelme bonfim", email: "rickelmebonfimdossantos@gmail.com", password: "123456", school_class: "33.01" },
  { name: "Keverllyn Sofia A.M", email: "keverllynalves@gmail.com", password: "Km-101214", school_class: "23.02" },
  { name: "Arthur Aragão de Sousa", email: "arthurargao123546@gmail.com", password: "arthur123564", school_class: "33.05" },
  { name: "Warlisson Alves da Silva", email: "warlisson.estudante@gmail.com", password: "warlisson123", school_class: "13.01" },
  { name: "Wemerson Carneiro da Silva", email: "22carneiroton@gmail.com", password: "tom2204", school_class: "33.02" },
  { name: "Pedro henrique brito", email: "phfernandes0708@gmail.com", password: "Ph07082008", school_class: "33.05" },
  { name: "CLEYSE KELY NEVES NOBREGA", email: "cleysek3lly007@gmail.com", password: "pierrot54288", school_class: "23.06" },
  { name: "CAUA OLIVEIRA DA LUZ ALENCAR", email: "cauaoliveiraa174@gmail.com", password: "571314va", school_class: "33.04" },
  { name: "NATHALY FERNANDES DE OLIVEIRA", email: "fernandesaalyynic0@gmail.com", password: "agu4viv4", school_class: "33.07" },
  { name: "Ana Klara Libânia Lima Nobrega", email: "anaklaralima2009@gmail.com", password: "lima1206", school_class: "33.09" },
  { name: "JAQUELINY N SILVA", email: "jacknascimento205@gmail.com", password: "Jack1306@", school_class: "33.01" },
  { name: "Livia Goncalves Santos", email: "liviagoncalves1802@gmail.com", password: "18022011", school_class: "13.04" },
  { name: "Ana Beatriz Barbosa da Rocha", email: "anabeatrizz4689@gmail.com", password: "ABB984670254", school_class: "13.01" },
  { name: "GABRIEL MORAIS DA SILVA", email: "gabrielmorais0978@gmail.com", password: "morais123", school_class: "23.03" },
  { name: "Jefersson Peres Ribeiro", email: "jeferssonperes4@gmail.com", password: "050286", school_class: "33.06" },
  { name: "Jhennifer Borges Moura da Silva", email: "jhenniferr005@gmail.com", password: "wynglesth21", school_class: "23.02" },
  { name: "Lidia Alves", email: "lidiaalvescostaesilva123@gmail.com", password: "123lidia", school_class: "23.04" },
  { name: "Davi gabriel maia marques", email: "davizinhogbrielmaia@gmail.com", password: "davigbriel1214", school_class: "23.05" },
  { name: "Jamily Magualhães", email: "diasjamily2010@gmail.com", password: "123456", school_class: "23.01" },
  { name: "Lady Laura Santiago Barros", email: "ladylaurasantiagobarros63@gmail.com", password: "santiago@2010", school_class: "13.07" },
  { name: "Ysadora Santos Da Cruz", email: "ysadoracruz08@gmail.com", password: "ysa_2008", school_class: "33.07" },
  { name: "Helena Coelho Burgos", email: "helenacoelhoburgos@gmail.com", password: "papelaria@2011", school_class: "13.07" },
  { name: "Micael Cezar Mendonça de Oliveira", email: "micaelcezar00@gmail.com", password: "#micael00", school_class: "23.03" },
  { name: "Anna Júllia Batista Moreira de Sousa", email: "batistaanna84@gmail.com", password: "12345678", school_class: "33.01" },
  { name: "Guilherme Aires silva martisn", email: "guilhermeairessilvamartisn@gmail.com", password: ".gul2008.", school_class: "33.05" },
  { name: "Ana Kelly", email: "kellyaraujoalmeida630@gmail.com", password: "anakkelly2009", school_class: "13.07" },
  { name: "VICTOR SOUZA SANTOS", email: "santosvicss17@gmail.com", password: "VSS#2008", school_class: "33.07" },
  { name: "jan carlos de oliveira", email: "jancarlosdeoliveira2009@gmail.com", password: "10642030", school_class: "33.08" },
  { name: "Kaio Henrique Resplandes Santana", email: "resplandeskaio@gmail.com", password: "kaiozin33", school_class: "23.06" },
  { name: "Dandara vitoria farias parente", email: "dandaravitoria476@gmail.com", password: "dandara.@05", school_class: "33.09" },
  { name: "Livia", email: "liviacristinasilvacosta@gmail.com", password: "Livia2008", school_class: "33.03" },
  { name: "Mateus emanuel barros da silva", email: "mateusemanuelbarros83@gmail.com", password: "timenicolly", school_class: "23.03" },
  { name: "Ayla Geovanna Rodrigues Maciel", email: "aylageovannar@gmail.com", password: "Ayla2020", school_class: "13.05" },
  { name: "Samir Elias Milagres Leime", email: "samirleime@gmail.com", password: "84409655", school_class: "33.02" },
  { name: "Ana Clara de sousa lima", email: "anaclarasousalima276@gmail.com", password: "071023", school_class: "33.09" },
  { name: "Rebeca Alencar do Nascimento", email: "rebeca.alencar0899@gmail.com", password: "OnePiece99", school_class: "33.07" },
  { name: "Guilherme carvalho reis", email: "guilhermecarvalho14@icloud.com", password: "Emily@2008", school_class: "33.08" },
  { name: "Jamilly Meneses da Silva Lima", email: "jamillymeneses04@gmail.com", password: "jose0285", school_class: "23.02" },
  { name: "Alexson rodrigues olimpio junior", email: "alexsonrodrigues75@gmail.com", password: "Alx.olimpio@123", school_class: "33.03" },
  { name: "Amanda Macedo dos Santos", email: "amandsmacedo22@gmail.com", password: "amandazk", school_class: "33.09" },
  { name: "Gabriel Gomes dos santos", email: "angolano619@gmail.com", password: "gabriel gomes777", school_class: "23.02" },
  { name: "Renaldo vieiras dos santos junior", email: "renaldojuniorchv@gmail.com", password: "12345", school_class: "23.03" },
  { name: "Maylline da Silva", email: "mayllinesilva5@gmail.com", password: "123456", school_class: "33.03" },
  { name: "Lyandra Sofia de Almeida Ferreira", email: "lyandraalmeida951@gmail.com", password: "lyandra001", school_class: "23.01" },
  { name: "Ana Gabriela Ferreira da Silva", email: "anagabrielaferreiradasilva7@gmail.com", password: "gabi20silva23", school_class: "33.08" },
  { name: "Michele Pacheco Vitorino", email: "michelepacheco240@gmail.com", password: "08022010", school_class: "23.02" },
  { name: "kemilly Ribeiro Sampaio", email: "kemillyribeiro003@gmail.com", password: "31122009", school_class: "23.03" },
  { name: "Dallyson Rhangel", email: "dallysons14@gmail.com", password: "230409", school_class: "23.02" },
  { name: "Vinicius Tavares Moraes", email: "vinicius6644y@gmail.com", password: "05042010", school_class: "23.01" },
  { name: "Joao Felipe Cardozo Oliveira", email: "joaofelipe20092050@gmail.com", password: "Jf#20092010", school_class: "33.01" },
  { name: "Lazaro lucas de lima neto", email: "lazarolucas216@gmail.com", password: "Lazo-012", school_class: "23.02" },
  { name: "Wynny Gabriele Coelho Oliveira", email: "coelhooliveirawynnygabriele@gmail.com", password: "Wynnycoelho123", school_class: "33.03" },
  { name: "Saulo Alves Oliveira", email: "notionsaulo@gmail.com", password: "Igatos123e", school_class: "13.06" },
  { name: "Eduarda da Silva", email: "eduardadasilvasantos2011@gmail.com", password: "San08081983", school_class: "13.04" },
  { name: "Isabela Assunção Monteiro Santos", email: "isabelaassuncaomon0012@gmail.com", password: "08452", school_class: "23.02" },
  { name: "Isadora Marquezine de Carvalho", email: "isadoramarquezine7@gmail.com", password: "Isadora1208", school_class: "23.06" },
  { name: "Luana Moura", email: "luahnameyer291@gmail.com", password: "meyerlinda", school_class: "23.03" },
  { name: "Ana Ester Alves dos Santos de Lima", email: "naee0018@gmail.com", password: "naee.2009", school_class: "23.01" },
  { name: "MIGUEL CANDIDO DE SOUSA GOMES", email: "EstudadorDePrego@gmail.com", password: "64201708349", school_class: "23.01" },
  { name: "Ana Vitória Rodrigues Paz", email: "anavitoriarodriguespaz@gmail.com", password: "avrp23", school_class: "23.01" },
  { name: "Oscar leal costa quirino", email: "oscarlealac@gmail.com", password: "Tiaamanda1234", school_class: "23.02" },
  { name: "Aluno 2", email: "aluno2@teste.com", password: "123456", school_class: "23.01" },
  { name: "Byanca Silva Ribeiro", email: "byancasilvaribeiro7@icloud.com", password: "byanca2009", school_class: "33.09" },
  { name: "Aluno 1", email: "aluno1@teste.com", password: "123456", school_class: "13.01" },
  { name: "Beatriz Araujo de Almeida", email: "beatrizaraujodealmeida6@gmail.com", password: "zica5224", school_class: "23.05" },
  { name: "Vitor Pedroza", email: "vitorpedrozza147@gmail.com", password: "nykTev-8hyjke-fuskoc", school_class: "13.04" },
  { name: "Amanda Gabryella", email: "amandagabypinheiro2009@gmail.com", password: "162303", school_class: "23.03" },
  { name: "Arthur Antonio", email: "arthurantoniovieira496@gmail.com", password: "D010912d", school_class: "33.01" },
  { name: "Henzo Gabriel Alves de Andrade", email: "2008henzogabriel@gmail.com", password: "Henzo2008", school_class: "13.05" },
  { name: "Davi de Souza Reis", email: "davisouzza636@gmail.com", password: "Dsr@122022", school_class: "23.06" },
  { name: "Ludielly de Oliveira abreu", email: "ludiellyoliveira067@gmail.com", password: "ludy_063", school_class: "33.08" },
  { name: "Mariana Gomes Cardoso", email: "mgomescardoso282@gmail.com", password: "Mww@9203", school_class: "33.09" },
  { name: "Guilherme Alves de Aguiar", email: "alvesdeaguiarguilherme71@gmail.com", password: "zxcvbnm@890", school_class: "33.09" },
  { name: "Laryssa Moreira Rodrigues", email: "laryssinha7778@gmail.com", password: "laryssa847918", school_class: "33.01" },
  { name: "Karla kelly bezerra de sousa", email: "karlakellysousa7@gmail.com", password: "kellys22", school_class: "33.02" },
  { name: "Giullia Leal Santos", email: "giullialealsantos@gmail.com", password: "Castroleal", school_class: "33.05" },
  { name: "Sophia Pinho Diniz", email: "sophiadiniz2208@gmail.com", password: "sophia6147", school_class: "23.04" },
  { name: "Ludielly de oliveira abreu", email: "oliveiraludielly8@gmail.com", password: "Dog_063@", school_class: "33.08" },
  { name: "Natalia Souza vidal", email: "natalividal476@gmail.com", password: "nataliaoedro", school_class: "33.07" },
  { name: "Amanda Barbosa Oliveira", email: "amandabarbosaoliveira14@gmail.com", password: "201427", school_class: "23.04" },
  { name: "Michael Morais santos", email: "michaelmoraissantosmoraissanto@gmail.com", password: "Kael157@", school_class: "33.09" },
  { name: "Marilia Vitória Julião Nascimento", email: "mari.marildinha09@icloud.com", password: "marilia.v", school_class: "33.09" },
  { name: "Mharia Fernanda Alves de Souza", email: "mhariafernanda.alves@gmail.com", password: "63991097599", school_class: "23.01" },
  { name: "Moisés Soares Lima", email: "moisessoareslima720@gmail.com", password: "Moises009", school_class: "13.07" },
  { name: "Davi luna", email: "daviluna1982@gmail.com", password: "40028922", school_class: "13.04" },
  { name: "Rafaella Oliveira marinho", email: "rafaellaoliveiranarinho8@gmail.com", password: "123456", school_class: "23.01" },
  { name: "JOHN WESLEY GERALDY SILVA TAVARE", email: "jwesleygeraldy@gmail.com", password: "estudo26", school_class: "33.08" },
  { name: "Livya Regina Pinheiro dos Santos", email: "livyaregina0@gmail.com", password: "luna2313", school_class: "23.01" },
  { name: "Evilyn Oliveira Morão", email: "thvevilyn@gmail.com", password: "moana369", school_class: "13.01" },
  { name: "Jhullya Evelly Andrade", email: "jhullyaandrade25@icloud.com", password: "Jhullya*", school_class: "33.01" },
  { name: "Mariana Santos de Oliveira Lopes", email: "marianalopesra@gmail.com", password: "xucsoP-qazjav-sadne4", school_class: "13.02" },
  { name: "AIRA DA DA SILVA PASSOS", email: "airapassos001@gmail.com", password: "lalinha 11", school_class: "33.08" },
  { name: "Henrique Siebert Marinho", email: "henriquesiebertmarinho946@gmail.com", password: "kike09/1.0", school_class: "23.02" },
  { name: "Yanna sophia isaias vieira", email: "yannasophia770@gmail.com", password: "16.04.10", school_class: "13.04" },
  { name: "Ana Clara Ferreira Conceição", email: "clana86404@gmail.com", password: "368425", school_class: "23.01" },
  { name: "ingryd thaissa Aires Ferreira rocha", email: "ingrydferreira84050@gmail.com", password: "ingrydaires1412", school_class: "33.09" },
  { name: "Mateus defino furtado", email: "mateusdelfinofurtado468@gmail.com", password: "Mateus.1", school_class: "33.07" },
  { name: "José Raimundo", email: "kertesz098@gmail.com", password: "Dd28102008__", school_class: "33.09" },
  { name: "Nicoly Cristhyne Alves Barbosa", email: "nicoly300311@gmail.com", password: "Nicoly.300319.", school_class: "13.07" },
  { name: "Aluno 3", email: "aluno3@teste.com", password: "123456", school_class: "33.01" },
  { name: "Jhonata pires da silva", email: "jhonatapires728@gmail.com", password: "123456789", school_class: "33.06" },
  { name: "João Victhor Sousa Lobato", email: "jvslobato12@gmail.com", password: "joao021008", school_class: "33.03" },
  { name: "Maria Eduarda Souza Magalhães", email: "souzamagalhaesmariaeduarda126@gmail.com", password: "duda@2009", school_class: "33.05" },
  { name: "Gabryella Borges", email: "gabryellaborges2701@gmail.com", password: "gabylinda123", school_class: "33.09" },
  { name: "Maria Eduarda Soares Tito", email: "soarestitomariaeduarda@gmail.com", password: "dudasoares", school_class: "33.06" },
  { name: "Iraci Júlia Rocha do Nascimento", email: "julianairaci12@gmail.com", password: "12345678", school_class: "33.09" },
  { name: "MARCUS VINICIUS WERNCKE TAVARES", email: "marcuswerncke123@gmail.com", password: "Marcus2018", school_class: "33.08" },
  { name: "Kauan Dos santos Oliveira", email: "kauandossantosoliveira87@gmail.com", password: "cmr8l6vb", school_class: "33.09" },
  { name: "Juliana Batista Xavier", email: "batistaxavierjuliana@gmail.com", password: "batista123", school_class: "23.05" },
  { name: "Raielly Camily Martins Gonçalves", email: "raiellycamilymartinsgoncalves@gmail.com", password: "17112009", school_class: "23.05" },
  { name: "GUSTAVO OLIVEIRA DE SOUZA", email: "gusttavosouzza008@gmail.com", password: "SOUZZA7889", school_class: "23.03" },
  { name: "Lucas Daniel Ferreira Rodrigues", email: "ferreirarodrigueslucasdaniel6@gmail.com", password: "10092010", school_class: "23.01" },
  { name: "GABRIEL BARBOSA FRANCO", email: "gabrielfrancobarbosa855@gmail.com", password: "vilmag2009", school_class: "23.01" },
  { name: "Sthefany Alves Aguiar Barbosa", email: "sthefanyalvesaguiar7@gmail.com", password: "sthefany", school_class: "33.09" },
  { name: "Lucas Alves Gomes", email: "gomeslual12@gmail.com", password: "lualgo12", school_class: "23.01" },
  { name: "Igor Ribeiro Rodrigues Barros", email: "igorrbarros7@gmail.com", password: "02@mores", school_class: "13.01" },
  { name: "Joao Pedro Carvalho", email: "jpcarvalho120@icloud.com", password: "@Jpc200813", school_class: "33.02" },
  { name: "Pietro Prado Aires De Souza", email: "pietroaires2010@gmail.com", password: "pietro2010", school_class: "23.01" },
  { name: "Maria Clara Francisca de sousa", email: "franciscadesousamariaclara@gmail.com", password: "mariaclara", school_class: "23.01" },
  { name: "Kaiky dima", email: "dkaike511@icloud.com", password: "NIKe.0409", school_class: "23.04" },
  { name: "Vitória Ferreira Abreu", email: "vitoriaferreiraabreu15@gmail.com", password: "vic1217*", school_class: "33.02" },
  { name: "Maria Eduarda Cândido Ribeiro Milhomer", email: "mariaeduardacrmilhomem@gmail.com", password: "Dudaalice01", school_class: "33.08" },
  { name: "Hanna Alves", email: "hannaalves5533@gmail.com", password: "123456", school_class: "33.05" },
  { name: "Davi Aguiar Amorim", email: "daviamorim902@gmail.com", password: "21102010", school_class: "23.01" },
  { name: "Victor Gabriel Costa dos Santos", email: "convertedigital13@gmail.com", password: "124578", school_class: "23.02" },
  { name: "Davi Guimarães", email: "daviguimaraespmw@gmail.com", password: "dg180825", school_class: "33.04" },
  { name: "Hattus Daniel Pereira Afonso", email: "hattusdaniel26@gmail.com", password: "07022010", school_class: "23.04" },
  { name: "Moisés Maurício Silva Viana", email: "moisesmauricio140@gmail.com", password: "senha_moises", school_class: "13.02" },
  { name: "Ana clara ferreira de souza", email: "ferreiradesouzaanaclara395@gmail.com", password: "Ana@0015", school_class: "33.04" },
  { name: "Danielly Freitas Lucas", email: "danyyifreitas@gmail.com", password: "dany074frt", school_class: "33.05" },
  { name: "JOSUÉ PEREIRA DE SÁ", email: "josuepereiradesa5@gmail.com", password: "1234", school_class: "23.01" },
  { name: "Eloa Alves e alves", email: "eloaalvesealves@gmail.com", password: "14012011", school_class: "13.05" },
  { name: "Glaucia Ribeiro Morais", email: "ribeiroglaucia2309@gmail.com", password: "morais2309", school_class: "23.02" },
  { name: "Maria Eduarda Campos Barros", email: "camposmadu926@gmail.com", password: "Madu1210", school_class: "33.09" },
  { name: "Melissa Farias Silva de Lucena", email: "melissafarias.lucena@gmail.com", password: "Melissa2010", school_class: "13.01" },
  { name: "Ana Júlia Gomes Melo", email: "anajuliagomesmelo46@gmail.com", password: "Ennila2215", school_class: "13.06" },
  { name: "Emanuelly da Silva", email: "dasilvaconeicaoemanuelly@gmail.com", password: "Avida1221", school_class: "33.04" },
  { name: "Guilherme santos de Souza feitosa", email: "guilhermecapa2020@gmail.com", password: "gui262672", school_class: "13.06" },
  { name: "THEODORO PANTA RENOVATO CEREZI", email: "theopanta295@gmail.com", password: "theo1701", school_class: "33.06" },
  { name: "Amanda Meneses Ribeiro Da Silva", email: "amandamenesesribeirodasilva75@gmail.com", password: "Amand@0408", school_class: "13.02" },
  { name: "ISABELLY DOS SANTOS DA CONCEICAO", email: "thelottiez@gmail.com", password: "2010", school_class: "13.07" },
  { name: "Maria Cecília dos Santos Ferreira", email: "mariaoficial973@gmail.com", password: "#M4ria", school_class: "23.04" },
  { name: "Lara Kevellyn Silvano Ribeiro", email: "larakevellysilvana@gmail.com", password: "lara", school_class: "13.05" },
  { name: "Islany melquiades de carvalhk", email: "islanymelquiadesdecarvalho@gmail.com", password: "lany8590", school_class: "33.08" },
  { name: "Natália Vieira Ramalho", email: "natalivramalho@gmail.com", password: "Natvr@2008", school_class: "33.04" },
  { name: "Heitor Falcão Duarte", email: "heitorfaduarte@gmail.com", password: "Amigao09", school_class: "23.01" },
  { name: "João Arthur Carneiro Sampaio", email: "sampaiojoaoarthur5@gmail.com", password: "Wendell13s", school_class: "23.01" },
  { name: "Maria Luiza da conceição nascimento", email: "kochikochimaico@gmail.com", password: "maria1234", school_class: "33.01" },
  { name: "Arthur de Oliveira Barbosa", email: "arthurolip12@gmail.com", password: "@Arthur12", school_class: "33.04" },
  { name: "Ana Gabriela Downar", email: "agabrieladownar@gmail.com", password: "Bela.300923", school_class: "33.01" },
  { name: "Vivian gonzaga", email: "ff6738280@gmail.com", password: "92447868", school_class: "23.04" },
  { name: "Kauã de Souza Lima", email: "limak5358@gmail.com", password: "123456", school_class: "33.09" },
  { name: "Gustavo de Sousa Santos", email: "gustavodesousasantos0@gmail.com", password: "fifamobile21", school_class: "23.03" },
  { name: "Yuri Reis leite", email: "yurireis72.02@gmail.com", password: "yreis1234", school_class: "33.03" },
  { name: "Thiago Viana Cortês", email: "thiagovianacortez848@gmail.com", password: "Thiago707#", school_class: "23.03" },
  { name: "Victor Andre Silva Sousa", email: "victorkiki014@gmail.com", password: "victor1930", school_class: "13.03" },
  { name: "GIOVANNA SANTOS RABELO", email: "santosrebelogiovanna@gmail.com", password: "Lunah2008357@", school_class: "33.06" },
  { name: "Ângelo Efraim Silva RODRIGUES", email: "angeloefraims@gmail.com", password: "Angelo2010@", school_class: "13.06" },
  { name: "Maisa Rodrigues Rocha", email: "marirocharios74@gmail.com", password: "maisa1234", school_class: "13.04" },
  { name: "BIANCA MAURICIO DE MORAES", email: "bmauriciodemoraes@gmail.com", password: "Bianca2705!", school_class: "23.04" },
  { name: "Aruany Gomes Alves", email: "arruanyg@gmail.com", password: "Aruanygomes2010", school_class: "23.04" },
  { name: "Vitória Nascimento", email: "vitorianascimento09@gmail.com", password: "TOIA27182011", school_class: "13.05" },
  { name: "Julia Helena dos Santos Corado", email: "juliahelenadossantoscorado126@gmail.com", password: "juliahelena2008", school_class: "33.05" },
  { name: "arthur elias maciel de moraes", email: "rtdmc71@gmail.com", password: "rtcria63", school_class: "33.01" },
  { name: "MATHEUS MOURAO CARNEIRO SOUZA", email: "matheusg4ff@gmail.com", password: "amsc2710", school_class: "23.01" },
  { name: "Murilo Silva Araújo Fernandes Mota", email: "murilomota897@gmail.com", password: "@Murilomota23", school_class: "33.06" },
  { name: "Safyra Santos", email: "silvafyrasantos@gmail.com", password: "safyra123", school_class: "23.04" },
  { name: "João Vitor Soares de Oliveira", email: "joaozinho406n@gmail.com", password: "joaoforte", school_class: "23.02" },
  { name: "Emanuel Coelho Torres", email: "emanuelcolho2@gmail.com", password: "futhor-jujjet-riBfu1", school_class: "23.03" },
  { name: "MATHEUS MORAES BRAGA", email: "matheusbragamoraes6@gmail.com", password: "j160782f", school_class: "23.02" },
  { name: "Emanuel Davi Rocha da Silva Morais", email: "emanueldavi.rsm1997@gmail.com", password: "AkumaNoMi16", school_class: "13.07" },
  { name: "Naillany Jesus Bezerra Nascimento", email: "naillanyjesus23@gmail.com", password: "Nayleh1623", school_class: "33.04" },
  { name: "Nathalia Da Silva Costa", email: "tatysilvaykr@gmail.com", password: "napa1607", school_class: "33.02" },
  { name: "Hellen Cristina Conceição da Silva", email: "hellenconceicao79@gmail.com", password: "12345678", school_class: "33.06" },
  { name: "Ana Júlia Vargas Macedo", email: "anajuliavargasmacedo8@gmail.com", password: "Macedo12$", school_class: "13.05" },
  { name: "Livia Cristina", email: "liviacristinasivacos@gmail.com", password: "02062008", school_class: "33.03" },
  { name: "Marina Nascimento Moraes", email: "marinamoraes2496@gmail.com", password: "mari2406", school_class: "33.03" },
  { name: "Thayná Cristina Saraiva Arrua", email: "thaysaraiva5@gmail.com", password: "240309", school_class: "33.01" },
  { name: "Maria Eduarda Gomes Santana", email: "duda0087@icloud.com", password: "Lolla@123", school_class: "13.03" },
  { name: "Lucas gabriel rodrigues pereira", email: "lucasgabriel1415@gmail.com", password: "towgoJ-kyqpe5-guctiz", school_class: "23.05" },
  { name: "JOSE LUCAS SILVA SOUSA", email: "lucasl2870480@gmail.com", password: "10102010", school_class: "13.07" },
  { name: "Jamilly Magalhães Dias", email: "diasjamilly2010@gmail.com", password: "Sesese11-", school_class: "23.01" },
  { name: "Joelma Bonifácio Costa Domingues", email: "joelmabonifacio321@gmail.com", password: "Joelma3520#", school_class: "33.03" },
  { name: "Yasmim gracia de siqueira gomes", email: "yasmimgraciadesiqueiragomes@gmail.com", password: "20080510Ys@", school_class: "33.06" },
  { name: "Julia de Kassia soares de Sousa", email: "cassiajulia318@gmail.com", password: "1205", school_class: "23.01" },
  { name: "Davi Lopes da Silva", email: "davilopesdasilva168@gmail.com", password: "Familia@1", school_class: "13.07" },
  { name: "Ana Julia Oliveira Soares", email: "annajuliaoliveirasoarea5@gmail.com", password: "Aajulia4a", school_class: "33.04" },
  { name: "kaua sousa", email: "kauasousa7070@gmail.com", password: "kaua.11", school_class: "33.06" },
  { name: "Ana Clara Rodrigues Teixeira", email: "suzirodrigues211082@gmail.com", password: "Ana1415.", school_class: "33.04" },
  { name: "Samuel Porto Aguiar", email: "portosamuel441@gmail.com", password: "1234567", school_class: "33.02" },
  { name: "Heloisa Barros Vieira", email: "heloisabarrosvieira6@gmail.com", password: "pequenaHelo#23", school_class: "23.01" },
  { name: "Nathan Pereira Sales", email: "nathansales2020@gmail.com", password: "Nathansales@2020", school_class: "13.01" },
  { name: "Fernanda ribeiro silva", email: "fribeirodasilva978@gmail.com", password: "blmkyd-3fifpu-zaptas", school_class: "33.07" },
  { name: "bruna milhomem rossi", email: "rossibruna04@icloud.com", password: "Junior48#", school_class: "23.01" },
  { name: "Hannah Gouveia do Nascimento", email: "hannahgouveia16@gmail.com", password: "16122008", school_class: "33.08" },
  { name: "Carlos Eduardo Dias Dos Santos Silva", email: "ce058436@gmail.com", password: "c1rlos_722", school_class: "33.05" },
  { name: "João Pedro De Lima Neto", email: "jplimalindo08@gmail.com", password: "020209jp", school_class: "33.08" },
  { name: "Emanuel Ribeiro", email: "ribeirocostaemanuel3@gmail.com", password: "21042104e", school_class: "33.07" },
  { name: "Isabella Pereira Silva", email: "isabellapereirasilva698@gmail.com", password: "ysapereira06", school_class: "23.01" },
  { name: "Kauan Lopes Silva", email: "ksilvalopes2020@gmail.com", password: "deuspai25", school_class: "33.09" },
  { name: "Rafael Noleto", email: "rafaelnoletoestevam123@gmail.com", password: "rafael16", school_class: "33.04" },
  { name: "Murillo pereira marques", email: "murillopereiramarques913@gmail.com", password: "Murillo1616", school_class: "33.05" },
  { name: "Gabriel Rocha", email: "gilvanribeirodesousa238@gmail.com", password: "BIRL_157", school_class: "13.06" },
  { name: "Stephanye Piagem Leao Silva", email: "leaopiagenstephanye@gmail.com", password: "Stephanye.1", school_class: "23.03" },
  { name: "Deivyd Silva", email: "deivydsilvamartinsfilho8@gmail.com", password: "123456", school_class: "13.07" },
  { name: "João Pedro Sousa Montel", email: "monteljoao8@gmail.com", password: "joaopedro76", school_class: "33.04" },
  { name: "Lídia Rosa Farias Calixto", email: "lidiarosafariasc1@gmail.com", password: "Jesusvem25", school_class: "33.03" },
  { name: "ARTHUR ROCHA MORAIS", email: "arthurcrmv23@gmail.com", password: "242526Na*", school_class: "33.03" },
  { name: "Allex de Almeida Fernandes", email: "almeidaallex2@gmail.com", password: "198022", school_class: "33.07" },
  { name: "Renan Carvalho de Morais", email: "renangamerarts@gmail.com", password: "marinha2020", school_class: "33.09" },
  { name: "Angelina coelho dos santos", email: "angelinaasanto063@gmail.com", password: "123456", school_class: "23.02" },
  { name: "Rebeca Maria Martins Lima", email: "rebecamariamartinslima@gmail.com", password: "43291208", school_class: "23.04" },
  { name: "Rafael Brayan Alves Morais", email: "rafaelbrayan2009@gmail.com", password: "aluno123", school_class: "23.04" },
  { name: "David Oliveira Nascimento", email: "davidoliveiranascimento4@gmail.com", password: "davilomo123", school_class: "33.09" },
  { name: "Maria Eduarda", email: "mportofrutuoso@gmail.com", password: "123456", school_class: "33.07" },
  { name: "Emilly Gabrielly costa da silma", email: "emilygabrielycosta2010@gmail.com", password: "10012010Eg", school_class: "23.04" },
  { name: "Ana Beatriz Vieira", email: "anabeatrizpacini3@gmail.com", password: "010920-0", school_class: "23.05" },
  { name: "Arthur Teles Guida Pinheiro", email: "arthurteles6753@gmail.com", password: "434547", school_class: "13.06" },
  { name: "Luana Vitória Cosmo", email: "luanavitoriacosmo16@gmail.com", password: "luana35", school_class: "23.06" },
  { name: "Ysabella Parrião Nunes", email: "ysabellaparriao26@gmail.com", password: "@Pysa0426", school_class: "33.08" },
  { name: "Emanuely Karoline Matos de Jesus Santos", email: "emanuk2020@gmail.com", password: "Manu.Karoline2009", school_class: "23.05" },
  { name: "Gabrieli dos Santos de Souza", email: "gabrielisantos3110@gmail.com", password: "ingrydlinda1.0", school_class: "33.09" },
  { name: "Karla kelly bezerra de sousa", email: "karlakellybezerradesousa42@gmail.com", password: "karla2212", school_class: "33.02" },
  { name: "Noemi Noia", email: "noianoemi2@gmail.com", password: "vjnml2023", school_class: "13.03" },
  { name: "Daniel Sousa de Almeida", email: "danielsousadealmeida09@gmail.com", password: "29052008", school_class: "33.02" },
  { name: "Luana Vitória Cosmo", email: "cosmoluanavitoria@gmail.com", password: "lana20", school_class: "23.06" },
  { name: "Arthur Andrade Pires", email: "arthurpires433@gmail.com", password: "#arthur2020", school_class: "23.01" },
  { name: "Arthur Santana Lima", email: "arthursantana64587@gmail.com", password: "Hasantana", school_class: "23.04" },
  { name: "Stephanie Gabino Dias", email: "stephaniegabino758@gmail.com", password: "02391028", school_class: "33.07" },
  { name: "João Pedro Monteiro da Silva", email: "jjoaopedromonteirodasilva@gmail.com", password: "Jpmaroto@#007", school_class: "33.02" },
  { name: "ANA PAULA LIMA ALVES", email: "anapaulalimaalves38@gmail.com", password: "ana2011", school_class: "13.06" },
  { name: "Isabella pinto de sousa", email: "isabellapinto72.01@gmail.com", password: "cleiton123", school_class: "33.05" },
  { name: "Luciano da Silva", email: "silvaluciano9849@gmail.com", password: "silva123", school_class: "13.06" },
  { name: "Marisia Ester Ribeiro Alecrim", email: "estermarisia@gmail.com", password: "28082009", school_class: "23.03" },
  { name: "Enzo gabriel alves de souza", email: "enzodidiavk@gmail.com", password: "enzodidi123", school_class: "23.04" },
  { name: "Esther Alleranny Soares De Souza", email: "estherallerannysoares@gmail.com", password: "21JUNHO*", school_class: "13.04" },
  { name: "Vinícius Coimbra Fernandes", email: "viniciuscoimbra286@gmail.com", password: "marcilio15", school_class: "33.05" },
  { name: "Rebeca Martins Pinheiro Feitosa", email: "eurebecama@gmail.com", password: "123456", school_class: "23.01" },
  { name: "Levi Moroni Mendes", email: "levimoroni55@gmail.com", password: "LeviSeven1101", school_class: "13.07" },
  { name: "EMANUEL MAIA SOUZA", email: "emanuelmaiaa1@gmail.com", password: "emanuel102030405060708090", school_class: "23.01" },
  { name: "Queren Hapuque Novaes Pinto", email: "queren.hnp@gmail.com", password: "5213asitwas", school_class: "33.02" },
  { name: "Guilherme Reis Magalhães", email: "guidoreis7755@gmail.com", password: "775550", school_class: "33.08" },
  { name: "Helena dos Santos Alecrim Rodrigues", email: "helenaalecrimrodrigues@gmail.com", password: "123456", school_class: "13.04" },
  { name: "Thiago Alves Almeida", email: "thiagoaalmeida12@gmail.com", password: "Lua24078*", school_class: "33.03" },
  { name: "Maria Eduarda de Souza e Silva", email: "marcosalessandro0814@gmail.com", password: "batguw-Tysheb-vyqdi7", school_class: "13.07" },
  { name: "Mylla Eduarda da Silva Coutinho", email: "coutinhomyllaeduarda@gmail.com", password: "Mylla3456", school_class: "23.04" },
  { name: "Daniel Alves Romanielo", email: "danielalvesromanielo@gmail.com", password: "Romanielo2008@", school_class: "33.03" },
  { name: "Thiago Damacena Dos Santos", email: "thdamacena12@gmail.com", password: "Teste-123", school_class: "23.02" },
  { name: "João Victor Lima Gonçalves", email: "jlimagoncalves8@gmail.com", password: "030409joaovictor", school_class: "23.04" },
  { name: "ingride Sousa viana", email: "ingridesousa33@gmail.com", password: "23052008", school_class: "33.04" },
  { name: "Gabriel isaac Pereira", email: "gabrieu.isaac206@gmail.com", password: "qwer4321", school_class: "33.08" },
  { name: "Joao pedro alves martins", email: "pedrin12331100@gmail.com", password: "Pedro123321", school_class: "33.08" },
  { name: "Gabriel Andrade Ferreira", email: "gabz00985@gmail.com", password: "Gabsff4234202402", school_class: "13.04" },
  { name: "Julia Bezerra Dias", email: "juliadias2029@gmail.com", password: "RH2008", school_class: "33.01" },
  { name: "Vitinho", email: "vhralves2020@gmail.com", password: "2026victorribeiro", school_class: "33.07" },
  { name: "Joao paulo batista da silva", email: "jplbatistasilva@gmail.com", password: "kkkk.mmmmm", school_class: "23.04" },
  { name: "Ezequiel Sousa Ribeiro", email: "ezequielsousaribeiro134@gmail.com", password: "Ezequiel123.", school_class: "13.07" },
  { name: "Pedro hugo pereira da silva", email: "pedrohugopereiradasilva3@gmail.com", password: "cytciX-0rerwi-pymxit", school_class: "23.04" },
  { name: "Emilly Lima Diniz", email: "emillylimadiniz545@gmail.com", password: "Emilly123", school_class: "33.01" },
  { name: "Nicolas Silva Fortunato", email: "nicolsdfottunato@gmail.com", password: "NICOLASSILVA12", school_class: "23.03" },
  { name: "José Victor Clímaco da Silva", email: "josevictorclimacodasilva@gmail.com", password: "josepapa0897", school_class: "13.01" },
  { name: "Guilherme Reis Magalhães de Oliveira silv", email: "guilhermereis77555@gmail.com", password: "775555", school_class: "33.08" },
  { name: "Maria Laura Teixeira Costa", email: "teixeiracostamarialaura@gmail.com", password: "maria063", school_class: "33.08" },
  { name: "Marvin James da Silva Costa", email: "kaineglokai@gmail.com", password: "marvin@890.", school_class: "23.05" },
  { name: "Mônica Cristinny", email: "monicaa.cristinnyy@gmail.com", password: "12124040", school_class: "33.08" },
  { name: "Guylherme Oliveira de Souza Dourado", email: "guylhermedourado8@gmail.com", password: "guylherme.dourado#@", school_class: "33.04" },
  { name: "Sofia Ferreira Melo Silva", email: "sofiafmsoficial@gmail.com", password: "sofiaF3525", school_class: "33.07" },
  { name: "Arthur brandao aires", email: "airesbrandaoarthur@gmail.com", password: "huqwu7-dlgjum-kigroz", school_class: "23.01" },
  { name: "Joel Martino Cruz", email: "joelmartino243@gmail.com", password: "jmdm1750", school_class: "23.02" },
  { name: "gustavo oliveira dasilva", email: "gustavooliveiradasilva020@gmail.com", password: "352600", school_class: "33.07" },
  { name: "Matheus Sousa Silva", email: "sousateteus2023@gmail.com", password: "030400", school_class: "23.04" },
  { name: "IASMIN ESTER", email: "iasminesteer567@gmail.com", password: "lasmin84373889", school_class: "23.01" },
  { name: "WILLIAM MIRANDA SILVA BEZERRA", email: "mirandawilliam720@gmail.com", password: "William2009", school_class: "33.06" },
  { name: "Maria Clara Batista Medrado", email: "mcb.medrado22@gmail.com", password: "medrado03", school_class: "23.02" },
  { name: "Isadora lopes da silva", email: "lopesisadora967@gmail.com", password: "mari210102", school_class: "33.06" },
  { name: "Laielem Silva alencar", email: "silvalaelem@gmail.com", password: "cybqaq-vojpac-5qyMwa", school_class: "33.01" },
  { name: "WESLEY RIBEIRO DOS SANTOS", email: "wesleyribeiroo199@gmail.com", password: "wesley2008", school_class: "33.06" },
  { name: "Kauan Henrique Batista Da Mota", email: "tharla.sepco1@gmail.com", password: "Kauan1604", school_class: "33.03" },
  { name: "Nilziellen Maia Verissimo", email: "nilziellenmaia@gmail.com", password: "nilziellen17", school_class: "33.07" },
  { name: "THAWANNE LIMA DE OLIVEIRA", email: "Thawannenanneoliveira@gmail.com", password: "Narutinho05/02F!", school_class: "33.09" },
  { name: "Isack Aguiar Sá", email: "aguiarsaisack@gmail.com", password: "grif00", school_class: "23.04" },
  { name: "Tayla Vitoria Lopes Andre", email: "taylavictoriaandre@gmail.com", password: "Tayla123", school_class: "33.09" },
  { name: "joao pedro matarazzo", email: "mp.jao14@gmail.com", password: "Matarazzo16@", school_class: "33.09" },
  { name: "Hórus Fernandes", email: "horusbrito@gmail.com", password: "horus2580", school_class: "23.03" },
  { name: "Diana Isabela da Silva", email: "dianaisabela0806@gmail.com", password: "BORGESMALU", school_class: "13.02" },
  { name: "Marielly ferreira torres", email: "mariellyf40@gmail.com", password: "Bento18082020", school_class: "33.07" },
  { name: "Maria Vitória Aparecida Rodrigues dos an", email: "mv6421455@gmail.com", password: "vitoria2010", school_class: "13.06" },
  { name: "Rafael da chagas dos Santos", email: "csebastiao309@gmail.com", password: "gokublack", school_class: "23.03" },
  { name: "João Paulo Da Cunha Rodrigues", email: "Cunhajp53@gmail.com", password: "123456", school_class: "33.02" },
  { name: "Vitor Gabriel Bastos dos Santos", email: "vitorgabrielbastossantos@gmail.com", password: "19092009mlpnko", school_class: "23.04" },
  { name: "Arthur Henrique Ribeiro Pereira", email: "arthurh201013@gmail.com", password: "19301412", school_class: "23.05" },
  { name: "Kaiocezar", email: "kaio.cmdo2@gmail.com", password: "#password", school_class: "23.03" },
  { name: "Talitta Aniely da Silva Nascimento", email: "talittaaniely238@gmail.com", password: "Talitta2905", school_class: "13.05" },
  { name: "Rodrigo da Silva Garcia", email: "rodrigosilvagarcia29@gmail.com", password: "984427284ro", school_class: "23.06" },
  { name: "Richard", email: "Richardcostaluz123@gmail.com", password: "195005Ri", school_class: "33.09" }
];
